### ISSUE TITLE
Submit Workflow: Power Thesaurus

### ISSUE THREAD

**Issue by giovannicoppola** [alfredapp/gallery-edits#10]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/giovannicoppola/alfred-powerthesaurus

### Alfred Forum page

https://www.alfredforum.com/topic/10576-power-thesaurus-search

### Gallery page content

Author: [@clarencecastillo](https://www.alfredforum.com/profile/13462-clarencecastillo/) (migrated to Python3/Alfred 5 by [@giovanni](https://www.alfredforum.com/profile/7146-giovanni/))

## Usage

Search Power Thesaurus for synonyms of `<word>` with `pows <word>`
<img width="1067" alt="PowerThesaurusSyn" src="https://github.com/alfredapp/gallery-edits/assets/5774411/3a2c1788-5db3-485c-9995-30efbdcf6868">

Search Power Thesaurus for antonyms of `<word>` with `powa <word>`
<img width="1067" alt="PowerThesaurusAnto" src="https://github.com/alfredapp/gallery-edits/assets/5774411/cb99008d-b006-4296-9f9e-911f8a8cf12a">

* <kbd>↩</kbd> or <kbd>⌘</kbd><kbd>C</kbd>: Copy selected entry to the clipboard
* <kbd>⌘</kbd><kbd>L</kbd>: Show full query in Alfred's Large Text window
* <kbd>⌘</kbd><kbd>↩</kbd>: Open synonyms on [Power Thesaurus](https://www.powerthesaurus.org/)
* <kbd>^</kbd><kbd>↩</kbd>: Open antonyms on [Power Thesaurus](https://www.powerthesaurus.org/)
* <kbd>⌘</kbd><kbd>Y</kbd> (or tap <kbd>⇧</kbd>): Quick Look the selected result

### Tags

dictionary, thesaurus

### Bundled libraries

`requests`

**Comment by vitorgalvao** [comment]
Thank you. Did some tweaking and had to retake the screenshots because yours for some reason had massive padding. For future submissions, would you mind using another theme?

I know that crediting the original creator is important for you, so added a note at the bottom of the page.

Now live at http://alfred.app/workflows/giovanni/power-thesaurus/
