### ISSUE TITLE
Submit Workflow: reddit browser

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#11]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/chrisgrieser/alfred-reddit-browser

### Alfred Forum page

https://www.alfredforum.com/topic/20813-reddit-browser/

### Gallery page content

The workflow does not require a reddit account. 

## Usage
Select a subreddit via the `sub` keyword. You can also add hackernews to that list via the [Workflow's Configuration](https://www.alfredapp.com/help/workflows/user-configuration/).

<img alt="showcase subreddit selection" src="https://github.com/chrisgrieser/alfred-reddit-browser/assets/73286100/bf805e00-7a5e-4325-9069-ff273b2f6c06">

Browse the current subreddit via the `rr` keyword.
<img alt="showcase browsing a subreddit" src="https://github.com/chrisgrieser/alfred-reddit-browser/assets/73286100/8d675449-431c-4ba1-8e6f-a75e263ee942">

- <kbd>⏎</kbd>: Open Post on reddit.
- <kbd>⌘</kbd><kbd>⏎</kbd>: Switch to next subreddit.
- <kbd>⇧</kbd><kbd>⌘</kbd><kbd>⏎</kbd>: Switch to previous subreddit.
- <kbd>⌥</kbd><kbd>⏎</kbd>: Copy URL of post to clipboard.
- <kbd>⇧</kbd><kbd>⏎</kbd>: Open URL (if external link).
- <kbd>⌘</kbd><kbd>Y</kbd> (or tap <kbd>⇧</kbd>): Preview the result. You can use the arrow keys to preview to the next result. Mostly useful for images.

Various customization options, like marking new posts or saving the scrolling position, are available via the [Workflow's Configuration](https://www.alfredapp.com/help/workflows/user-configuration/).

### Tags

reddit, social-media

### Test data

use these as example subreddits:
```
macapps
commandline
ProgrammerHumor
```

### Homebrew dependencies

none

### Bundled libraries

none

**Comment by vitorgalvao** [comment]
Thank you. [It’s live](https://alfred.app/workflows/chrisgrieser/reddit-browser/).
