### ISSUE TITLE
Submit Workflow: Convert

### ISSUE THREAD

**Issue by giovannicoppola** [alfredapp/gallery-edits#12]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/giovannicoppola/alfred-convert

### Alfred Forum page

https://www.alfredforum.com/topic/3980-offline-unit-conversion-workflow

### Gallery page content

Convert between different units offline in Alfred.
## Usage
`conv <quantity> <from unit> [<to unit>]` — Perform a conversion
<img width="605" alt="image" src="https://github.com/alfredapp/gallery-edits/assets/5774411/905fc140-fd7a-4dad-8c56-b05f05a0dcc4">

- <kbd>↩</kbd>: Copy result without thousands separator to pasteboard
- <kbd>⌘</kbd><kbd>C</kbd>: Copy result with thousands separator to pasteboard
- <kbd>⌘</kbd><kbd>↩</kbd>: Add/remove destination unit as default for this dimensionality
- <kbd>⌘</kbd><kbd>L</kbd>: Show result in Alfred's Large Type window

`convinfo` — View help file and information about the workflow, or edit custom units and active currencies
<img width="605" alt="image" src="https://github.com/alfredapp/gallery-edits/assets/5774411/989a9c5c-b823-44bf-bacb-507bc5045d5c">

- `View Help File` — Open this page in your browser
- `View All Supported Currencies` — View/filter the list of all supported currencies in Alfred
- `Edit Active Currencies` — Edit the list of active currencies in your default text editor
- `Edit Custom Units` — Edit the list of custom currencies in your default text editor

## Credits
- Forked from the original by Dean Jackson ([@deanishe](https://www.alfredforum.com/profile/5235-deanishe/)).
- [Pint](https://pint.readthedocs.io/en/stable/) library

### Tags

conversion, currency, exchange

### Bundled libraries

`workflow`, `pint`

**Comment by vitorgalvao** [comment]
The screenshots are still using the theme with the huge padding. In addition, please follow the [style guide](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Page%20Style%20Guide.md): instructions should flow with the screenshots and be written like text instead of having separate screenshots and bullet points.

Everything that is mentioned should have screenshots, meaning one for `conv` and one for `convinfo`.

Also, there’s a typo in the first configuration: it says `App key` instead of `API key`.

<img width="398" alt="image" src="https://github.com/alfredapp/gallery-edits/assets/1699443/c84ba371-0f89-47d7-b17b-ace4584a9496">

**Comment by vitorgalvao** [comment]
Thank you. Will be live later today at https://alfred.app/workflows/giovanni/convert/.
