### ISSUE TITLE
Submit Workflow: Fakeum

### ISSUE THREAD

**Issue by giovannicoppola** [alfredapp/gallery-edits#13]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/giovannicoppola/alfred-fakeum

### Alfred Forum page

https://www.alfredforum.com/topic/20620-fakeum-%E2%80%94-generate-fake-test-datasets-in-alfred/

### Gallery page content

**Fakeum — Generate fake test datasets in Alfred**
## Usage
`fake [<query>]` — List/filter available fake data types
<img width="605" alt="image" src="https://github.com/alfredapp/gallery-edits/assets/5774411/ef64cd16-8465-482d-b397-9b49ceccf558">
- <kbd>↩</kbd>, <kbd>⌘</kbd><kbd>C</kbd> or <kbd>⌘</kbd><kbd>NUM</kbd>: Copy one fake datum to clipboard
- <kbd>⌘</kbd><kbd>↩</kbd>: Paste fake datum into frontmost app
- <kbd>⇥</kbd>: Specify number of datasets to copy to clipboard
- <kbd>⌘</kbd><kbd>L</kbd>: Show generated data in Alfred's Large Text window

`fakeconfig [<query>]` — Edit workflow settings
<img width="605" alt="image" src="https://github.com/alfredapp/gallery-edits/assets/5774411/0dd5959b-07c2-4f47-92d3-11370093c681">

- `Notifications` — Turn notifications on/off
    - <kbd>↩</kbd>: Toggle on/off
- `Locales` — Turn locales for fake data on/off
    - <kbd>↩</kbd>: Show & edit active locales
- `[<query>]` — Filter locales
    - <kbd>↩</kbd>: — Toggle locale on/off

There is also a Snippet Trigger (`xxfake` by default) to insert fake data directly into other applications.

## Credits
- Forked from the original by Dean Jackson ([@deanishe](https://www.alfredforum.com/profile/5235-deanishe/)).
- [faker](https://github.com/joke2k/faker) library

### Tags

fake-data

### Bundled libraries

`workflow`, `faker`

**Comment by vitorgalvao** [comment]
Same requests from https://github.com/alfredapp/gallery-edits/issues/12#issuecomment-1744649077 apply. This is a major reason why I ask for one submission at a time: so you can avoid effort in one direction multiple times when there’s something in the process which needs fixing.

**Comment by giovannicoppola** [comment]
sorry! I still don't seem to see this padding issue, but I now used a default theme.

**Comment by vitorgalvao** [comment]
Thank you, much improved. I still made some tweaks, e.g.:

> `fake [<query>]` — List/filter available fake data types

to

> Search available fake data types via the `fake` keyword

To follow the style.

> There is also a Snippet Trigger (`xxfake` by default) to insert fake data directly into other applications.

Like Hotkeys, Snippet Triggers are stripped on import (imagine if a workflow had trigger which were something common another person typed). I’ll make a not about it, though.

This one will be live later today at https://alfred.app/workflows/giovanni/fakeum/.
