### ISSUE TITLE
Suggest Edit: epilande/browser-tabs

### ISSUE THREAD

**Issue by mdavenhill** [alfredapp/gallery-edits#14]
### Gallery URL

https://alfred.app/workflows/epilande/browser-tabs/

### About

Love the Workflow, but wish I could use it to close tabs. (Or better yet: close all duplicate tabs) 

Sometimes when shopping online, I end up with multiple duplicate tabs. These can be difficult to distinguish in the browser window. However, when I search for tabs using this workflow, the duplicates are usually lined up. So it would be great if they were *always* lined up, and if we could just close all duplicates in one command.

Just a thought. Cheers!

**Comment by vitorgalvao** [comment]
If you want to request a new feature for a workflow, click the `Website` link and contact the workflow’s creator. The link you clicked is to suggest edits to the Gallery page.

**Comment by mdavenhill** [comment]
Oops! Apologies! Thank you for the redirect :)
