### ISSUE TITLE
Suggest Edit: biatidigital/calculate-anything

### ISSUE THREAD

**Issue by gingerbeardman** [alfredapp/gallery-edits#15]
### Gallery URL

https://alfred.app/workflows/biatidigital/calculate-anything/

### Website

https://github.com/biati-digital/alfred-calculate-anything/

### Report Bug

https://github.com/biati-digital/alfred-calculate-anything/issues/

### About

Forum link is incorrect, not sure if there is one for this workflow

**Comment by vitorgalvao** [comment]
Indeed [there is a link](https://www.alfredforum.com/topic/13974-calculate-anything). Fix will be live in a few minutes. Thank you for the report.
