### ISSUE TITLE
Submit Workflow: Homebrew Search

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#16]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/chrisgrieser/alfred-homebrew

### Alfred Forum page

https://www.alfredforum.com/topic/20992-alfred-homebrew-search/

## Usage
Search for a Homebrew package via the `bi` keyword.

<img alt="showcase brew install" src="https://github.com/chrisgrieser/alfred-homebrew/assets/73286100/a46f48c7-e5ce-4eb2-aeb1-451231043b26">

+ <kbd>⏎</kbd>: Install the package (`brew install`) in the Terminal. (Uses the terminal app you have configured [in your Alfred settings](https://www.alfredapp.com/help/features/terminal/).)
+ <kbd>⌘</kbd><kbd>⏎</kbd>: Open the package's homepage (`brew home`).
+ <kbd>⌥</kbd><kbd>⏎</kbd>: Copy the package's homepage to the clipboard.
+ <kbd>⇧</kbd><kbd>⏎</kbd>: Show package information (`brew info`) in Large Text.

### Uninstallation & Reinstallation
Uninstall a package via the `bu` keyword (`brew uninstall`). Optionally, use the `--zap` option for a clean uninstallation.

<img alt="showcase brew uninstall" src="https://github.com/chrisgrieser/alfred-homebrew/assets/73286100/b40a4300-7b2d-44fd-89a3-90fdf0190271">

Reinstall a package already installed on your system via the `br` keyword (`brew reinstall`).

<img alt="showcase brew reinstall" src="https://github.com/chrisgrieser/alfred-homebrew/assets/73286100/f7a30be0-64c0-42ef-80d6-969a73922706">

Search and install fonts available in the [Homebrew font tap](https://github.com/Homebrew/homebrew-cask-fonts) via the `bf` keyword (`brew install font-…`).

<img alt="showcase brew font install" src="https://github.com/chrisgrieser/alfred-homebrew/assets/73286100/5bb4c0da-a366-49f4-b5be-38d641cc5a2f">

### Tags

search, packages, homebrew

### Test data

–

### Homebrew dependencies

Homebrew itself must be installed on the user's system.

### Bundled libraries

–

**Comment by vitorgalvao** [comment]
Missing screenshot for `br`, `bu`, and `bf`. I can take them, but if you’re able to provide (without the highlight on the text field) them I can get this is in sooner.

**Comment by chrisgrieser** [comment]
all done

**Comment by vitorgalvao** [comment]
Thank you. [It’s live](https://alfred.app/workflows/chrisgrieser/homebrew-search/).
