### ISSUE TITLE
Submit Workflow: PDF Summarizer

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#17]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/chrisgrieser/pdf-summarizer-alfred

### Alfred Forum page

https://www.alfredforum.com/topic/20847-pdf-summarizer/

## Setup
Requires a ChatPDF API key, which is currently free for 5000 PDF pages / 500 requests per month.

**Get a ChatPDF API key:**
1. Go to <https://www.chatpdf.com/>
2. Scroll to the very bottom of the page.
3. In the footer, click `My Account`. You will be prompted to create an account if you do not have one yet.
4. In `My Account`, expand the `Developer` settings. You will find your API key there:

<img src="https://raw.githubusercontent.com/chrisgrieser/pdf-summarizer-alfred/main/assets/how-to-get-api-key.png" alt="how to find the API key">

## Usage
<img width="60%" alt="Showcase Universal Action" src="https://github.com/chrisgrieser/pdf-summarizer-alfred/assets/73286100/a4c8e7e7-cb56-4727-9a0e-ddfc91461c11">

Use the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/) on a PDF to send a request for a summary. Alternative, configure a [hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) to trigger the summary on a PDF file selected in Finder.

### Tags

pdf, ai

**Comment by vitorgalvao** [comment]
Missing a screenshot of the Universal Action. I can take it, but if you’re able to provide it I can get this in sooner.

**Comment by vitorgalvao** [comment]
Thank you. Will be live later today at https://alfred.app/workflows/chrisgrieser/pdf-summarizer/.
