### ISSUE TITLE
Submit Workflow: Tot Integration

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#18]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/chrisgrieser/tot-alfred

### Alfred Forum page

https://www.alfredforum.com/topic/20999-totapp-integration/

## Usage
Access your Dots via the keyword `tot`.
<img alt="Showcase Image" src="https://github.com/chrisgrieser/tot-alfred/assets/73286100/d2aa38d9-3b38-4dbe-9041-41ab6bef91d3">

- <kbd>⏎</kbd> Open the Dot.
- <kbd>⌘</kbd><kbd>⏎</kbd> Append to the Dot.
- <kbd>⌥</kbd><kbd>⏎</kbd> Copy the contents of the Dot.
- <kbd>⌃</kbd><kbd>⏎</kbd> Delete the Dot.

### Quick Appending
Quickly append to a pre-selected Dot via the keyword `qq`.

Configure the [Hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) for quick appending to a configurable Dot.
- If a browser is frontmost, appends the current browser tab as Markdown link.
- In any other app, appends the selected text.
- If Tot is frontmost, opens all URLs in the current Dot instead.

### Tags

notes,markdown

**Comment by vitorgalvao** [comment]
This one has been [live](https://alfred.app/workflows/chrisgrieser/tot/) since earlier today.
