### ISSUE TITLE
Submit Workflow: Pass-Client

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#19]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/chrisgrieser/alfred-pass

### Alfred Forum page

https://www.alfredforum.com/topic/20664-alfred-as-a-client-for-the-pass-cli/

## Setup
1. Setup `pass` with a GPG key. See the [Pass Website](https://www.passwordstore.org/) for further information.
2. Configure `pinentry-mac` as your `pinentry-program`:

   ```bash
   [[ -d "$HOME/.gnupg" ]] || mkdir "$HOME/.gnupg"
   echo "pinentry-program $(brew --prefix)/bin/pinentry-mac" > $HOME/.gnupg/gpg-agent.conf
   gpgconf --kill gpg-agent # restart the agent
   ```

## Usage
Search your passwords via the keyword `pw`.

<img src="https://raw.githubusercontent.com/chrisgrieser/alfred-pass/main/assets/showcase.png" alt="showcase">

- <kbd>⏎</kbd>: Copy password to the clipboard. If your search query does not
  find an entry, you can directly create a new entry by pressing `↵`. You are
  then be prompted for a folder to place the new entry in. The password of the
  new entry is auto-generated based on your `pass` settings, or can be inserted
  from your clipboard.
- <kbd>⌘</kbd><kbd>⏎</kbd>: Edit entry in your Terminal, using [the Terminal configured in your Alfred settings](https://www.alfredapp.com/help/features/terminal/) and your `$EDITOR`.
- <kbd>⌥</kbd><kbd>⏎</kbd>: Reveal `.gpg` file of the entry in Finder.
- <kbd>⌃</kbd><kbd>⏎</kbd>: Delete the entry.
- <kbd>⇧</kbd><kbd>⏎</kbd>: Show details of the entry. Select any one of them to
  copy the value to your clipboard.

### Tags

password-manager

### Homebrew dependencies

- pass
- pinentry-mac

**Comment by vitorgalvao** [comment]
Thank you. Will be live later today at https://alfred.app/workflows/chrisgrieser/pass/.

On another note, in the `clear-copy` script you have the following:

> \# INFO password clearing is implemented via this script rather than using pass'
> \# built-in functionality because the built-in functionality requires using `pass
> \# --clip` which saves the password to in a non-transiently, meaning it is
> \# readable in Alfred's clipboard history.

I’m not overly familiar with `pass`, but it’s worth noting Alfred respects `org.nspasteboard.ConcealedType`, which is a standard way of marking data as private in the clipboard. Apps which store sensitive data (e.g. 1Password) set that flag when copying sensitive information. That means the data will still be in your clipboard but won’t be saved. You can read more at http://nspasteboard.org. I mention it because you may want to submit a PR or discuss it with the `pass` developers. Note this does not delete data on a timer.

For your own reference, [the 1Password workflow implements a simple way to save data that way from JXA](https://github.com/alfredapp/1password-workflow/blob/63a3eac9f070dc9441388da81e90e698ce3d7e93/Workflow/1password.js#L75L83).

**Comment by chrisgrieser** [comment]
yeah, I tried out different variations, and indeed, `pass` does not respect `ConcealedType`, which is why I went for that workaround. Good point on raising the info directly with the devs though
