### ISSUE TITLE
Submit Workflow: Emoji Wine

### ISSUE THREAD

**Issue by BenjaminOddou** [alfredapp/gallery-edits#2]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/BenjaminOddou/alfred-emoji-wine

### Alfred Forum page

https://www.alfredforum.com/topic/20333-emoji-wine/

## Usage

Search emojis with the `wine` keyword.

![Capture d’écran 2023-07-16 à 14 43 22](https://github.com/alfredapp/gallery-edits/assets/85166574/53d80382-337e-46c7-8328-dfb326a0332e)

<kbd>↩︎</kbd>: Copy the emoji to the clipboard.
<kbd>⌘</kbd><kbd>↩︎</kbd>: Paste the emoji to frontmost application.
<kbd>⇧</kbd><kbd>↩︎</kbd>: Open the emojipedia page.

The `harvest` keyword is used to refresh the API and manage tags. Tags are used to search a group of emojis with custom keywords or sentences.

![Capture d’écran 2023-07-16 à 14 50 42](https://github.com/alfredapp/gallery-edits/assets/85166574/a60a6bc1-5d7f-4028-bac5-29911a4bd240)

![Capture d’écran 2023-07-16 à 14 57 27](https://github.com/alfredapp/gallery-edits/assets/85166574/468c4aef-06bb-4974-a283-5aed31a3a1fe)

![Capture d’écran 2023-07-16 à 14 57 42](https://github.com/alfredapp/gallery-edits/assets/85166574/2c0f5775-a932-4349-b26c-207eea87c8c0)

### Tags

emoji, api, emoji-picker, emojipedia

### Test data

/

### Homebrew dependencies

[Pillow](https://formulae.brew.sh/formula/pillow)

### Bundled libraries

No bundled library.

**Comment by BenjaminOddou** [comment]
Example of tags (must be named `tags-<en/fr...>.json`) to be placed in `~/Library/Application Support/Alfred/Workflow Data/com.benjamino.emoji_wine`.

```json
[
    {
        "id": "7df02fe8d440",
        "title": "French Touch",
        "emojis": [
            "🥐",
            "🧀",
            "🍾",
            "🇫🇷",
            "🥖",
            "🍷"
        ]
    },
    {
        "id": "078f7f569d84",
        "title": "Unicode 15.0",
        "emojis": [
            "🫸🏽",
            "🪈",
            "🪭",
            "🫷🏽",
            "🫨",
            "🫸🏼",
            "🫏",
            "🪼",
            "🫸🏻",
            "🐦‍⬛",
            "🫷🏼",
            "🩵",
            "🫚",
            "🫸",
            "🩶",
            "🫷🏾",
            "🪇",
            "🫛",
            "🫎",
            "🪮",
            "🪻",
            "🫷🏻",
            "🫸🏾",
            "🩷",
            "🫷🏿",
            "🫸🏿",
            "🫷",
            "🛜",
            "🪽",
            "🪿",
            "🪯"
        ]
    }
]
```

**Comment by vitorgalvao** [comment]
Unfortunately, the Pillow library is making this impossible to run. Those binaries, the `.so` files, are not signed and thus are stopped by macOS. Sometimes those aren’t actually crucial and can be deleted without repercussions, but in this case that doesn’t work.

However, I looked around and [`pillow` is available as a Homebrew formula](https://formulae.brew.sh/formula/pillow) so it may be possible for you to shift to use that instead? Then `pillow` would be listed as a dependency of the workflow and installable via the [dependencies manager](https://www.alfredapp.com/help/kb/dependencies/).

This is tangential, but it looks like you have installed the library with a Homebrewed Python. They should always be installed with the Python which ships with macOS (`/usr/bin/python3`) to ensure they work on most people’s installations. That doesn’t matter for this case though, as it’s not the source of the issue.

**Comment by BenjaminOddou** [comment]
@vitorgalvao, indeed I didn't realized that I was shipping unsigned binaries. Normally I am putting all my python dependencies along with the workflow, that's why !

I can remove the lib folder inside the workflow and make pillow in the list of homebrew package (I am gonna change the docs also) then it should be good to go ? Is there other improvements I should do ?

Many thanks in advance.

**Comment by BenjaminOddou** [comment]
@vitorgalvao, I updated the workflow and removed the embedded pillow library. Now it's required as a Homebrew dependency.

**Comment by vitorgalvao** [comment]
Thank you for the submission and fast turnaround. It will list not only pillow as a dependency, but python3 as well since it needs a Homebrew version. That required an extra bit of consideration, but everything looks fine. Should be live at https://alfred.app/workflows/benjaminoddou/emoji-wine/ during the day tomorrow.
