### ISSUE TITLE
Submit Workflow: PDF Annotation Extractor

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#20]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/chrisgrieser/pdf-annotation-extractor-alfred

## Requirements
- The *PDF Annotation Extractor* works on any PDF that has valid annotations
  saved *in the PDF file*. Some PDF readers like __Skim__ or __Zotero 6__ do not
  store annotations in the PDF itself by default.
- References saves as a BibTex Library.
- The filename of the PDF must be *exactly* the citekey (without `@`),
  optionally followed by an underscore and some text like
  `{citekey}_{title}.pdf`. The citekey must not contain underscores (`_`).

## Usage
Search for a PDF file from which you want to extract the annotations using the keyword `anno`. Alternatively, use the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/) or configure a [hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) to trigger the annotation extractions.

### Annotation Types extracted
- Highlight ➡️ bullet point, quoting text and prepending the comment
- Free Comment ➡️ blockquote of the comment text
- Strikethrough ➡️ Markdown strikethrough
- Rectangle ➡️ image
- Underlines ➡️ sent to [SideNotes](https://www.apptorium.com/sidenotes) (if not
  installed, they are ignored)

### Tags

pdf,notes,academic

### Homebrew dependencies

pdfannots2json, though it is not a regular package but only available via as a tap. It's installed via `brew install mgmeyers/pdfannots2json/pdfannots2json`

**Comment by chrisgrieser** [comment]
To be honest, I am not sure how much should go into the Gallery description, since this is one of the more complex workflows. Likely requiring another "Note from the Alfred Team", that users should go to the GitHub readme for further instructions?

**Comment by vitorgalvao** [comment]
> though it is not a regular package

I didn’t have the chance to look into it before, but unfortunately that means it can’t go in at this point. The submission form mentions that Homebrew dependencies must be from the official core tap, as that offers an extra layer of scrutiny and attention to the packages.

**Comment by chrisgrieser** [comment]
Ah, I see. Yeah, I can understand that
