### ISSUE TITLE
Submit Workflow: [Zothero]

### ISSUE THREAD

**Issue by giovannicoppola** [alfredapp/gallery-edits#21]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/giovannicoppola/zothero

### Alfred Forum page

https://www.alfredforum.com/topic/11658-zothero-%E2%80%94-generate-zotero-citations-in-alfred

### Gallery page content

Search and copy citations from your Zotero database
This workflow requires [Zotero](https://www.zotero.org/)
 
## Usage
Perform full-text search across your Zotero database, including only searching specific fields, via the `zot` keyword

![zothero](https://github.com/alfredapp/gallery-edits/assets/5774411/f6439b9c-36a2-4f91-adc7-31e701755741)

- <kbd>↩</kbd>, <kbd>⌘</kbd><kbd>C</kbd> or <kbd>⌘</kbd><kbd>NUM</kbd>: Copy one fake datum to clipboard
- <kbd>↩</kbd>: Open the entry in Zotero
- <kbd>⌘</kbd><kbd>↩</kbd>: Copy citation to the pasteboard
- <kbd>⌥</kbd><kbd>↩</kbd>: Copy bibliography-style citation to the pasteboard
- <kbd>⇧</kbd><kbd>↩</kbd>: View entry attachments (if present)
- <kbd>^</kbd><kbd>↩</kbd>: View all citation styles
- View and edit workflow configuration via the `zotconf` keyword
- Zothero can also be triggered by typing a snippet (which you must first assign yourself in `Alfred Preferences`)

## Credits
- Forked from the original by Dean Jackson ([@deanishe](https://www.alfredforum.com/profile/5235-deanishe/)).

### Tags

references, citations, literature, academia

### Test data

demo library: Import in Zotero (File>Import) before running the workflow
[DemoLibrary.rdf.zip](https://github.com/alfredapp/gallery-edits/files/13460799/DemoLibrary.rdf.zip)

### Bundled libraries

workflow, zothero, cite

**Comment by vitorgalvao** [comment]
Thank you. Will be live soon at https://alfred.app/workflows/giovanni/zothero/.
