### ISSUE TITLE
Submit Workflow: [Outlook Suite]

### ISSUE THREAD

**Issue by giovannicoppola** [alfredapp/gallery-edits#22]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/giovannicoppola/alfred-outlookSuite

### Alfred Forum page

https://www.alfredforum.com/topic/20535-introducing-alfred-outlooksuite-%F0%9F%93%AC-a-suite-of-tools-to-interact-with-microsoft-outlook-via-alfred/

### Gallery page content

Interact with Microsoft Outlook

_Note_: Many of the functions of this package will not work with the new, electron-based, 'New Outlook' interface, as AppleScript is not supported. Uncheck `New Outlook` in the `File` menu in Outlook to switch to the legacy version.

Consult the Workflow’s [website](https://github.com/giovannicoppola/alfred-outlookSuite) for the full feature set and documentation.

## Usage
- Search your Outlook email via the `olk` keyword
![outlookSuite3](https://github.com/alfredapp/gallery-edits/assets/5774411/4db60a0b-5140-4e0c-bfd0-23cebb2e3d6d)

- Save an Outlook email via the `ols` keyword
- Snooze an Outlook email via the `olz` keyword
![snooze](https://github.com/alfredapp/gallery-edits/assets/5774411/b5119a52-ba46-481e-beb9-07381d38618e)

- Draft an Outlook email via the `em` keyword

![draft](https://github.com/alfredapp/gallery-edits/assets/5774411/4fd92c00-cadd-48c4-b75a-21188e49d49b)

- gmail-like search strings, listed below, supported (remember to set the `MYSELF` variable in the `Workflow Configuration`). 
	- `from:` (including `from:me`). Replace space with underscore if you want to specify the whole name (e.g. `from:john_appleseed`)
	- `to:` (including `to:me`)
	- `cc:` (including `cc:me`)
	- `subject:`,  `has:attach`, `is:unread`, `is:read`, `is:important`, `is:unimportant`  
	- `folder:` (note: replace spaces with underscores if the folder name contains spaces, e.g. `folder:sent_items`)
	- `-text` to exclude text 
	- `account:` to filter by Exchange account
	- `--a` to sort by increasing date (oldest first)
	- `since:n` will return email received in the last `n` days. `w` and `m` are supported for months and weeks, respectively (e.g. `since:2w`).
	- `sq:` will open a list of saved queries
- Once an email of interest has been identified, the following actions are possible:
	- <kbd>↩</kbd>: Open the email in Outlook
	- <kbd>^</kbd><kbd>↩</kbd>: Show all the messages in the thread
	- <kbd>⇧</kbd><kbd>↩</kbd>:Show message in large font (and copy to clipboard)

### Tags

outlook, email, productivity

**Comment by vitorgalvao** [comment]
[Same issue with screenshots.](https://github.com/alfredapp/gallery-edits/issues/24#issuecomment-1841616488) Plus missing screenshots for the other keywords listed at the top.

**Comment by vitorgalvao** [comment]
Thank you. Will be available later today at https://alfred.app/workflows/giovanni/outlook-suite/.
