### ISSUE TITLE
Submit Workflow: [AlfreDo]

### ISSUE THREAD

**Issue by giovannicoppola** [alfredapp/gallery-edits#23]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/giovannicoppola/AlfreDo

### Alfred Forum page

https://www.alfredforum.com/topic/20361-introducing-alfredo-a-workflow-for-todoist-%E2%9C%85/

### Gallery page content

An Alfred Workflow for [Todoist](https://todoist.com/).
_Note_: app not created by, affiliated with, or supported by Doist.
This workflow requires a [Todoist](https://todoist.com/) account.

## Usage
List your Todoist tasks via the keywords:
`!1`: due today
`!2`: overdue
`!3`: all tasks
Use multiple strings, or label/projects to refine search. Use `@` to enter one or more labels, `#` to enter a project/section.
Create a new task via the `!!!` keyword

![demo](https://github.com/alfredapp/gallery-edits/assets/5774411/3a5261d6-3586-4af5-8cbf-20f060f3b6a1)

Once a task is selected:
- <kbd>↩</kbd>: Open the task on [Todoist](https://todoist.com/) (default) or in the Todoist app, based on user preference
- <kbd>⇧</kbd><kbd>↩</kbd>: Complete the task
- <kbd>^</kbd><kbd>↩</kbd>: Reschedule the task. Choose one of the options, or enter a date in international format, or enter a number of days. 
![reschedule](https://github.com/alfredapp/gallery-edits/assets/5774411/02a317a0-be2a-445f-a689-0a60c3e64793)

Create new tasks by selecting text in any app via the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/)
![universalAction](https://github.com/alfredapp/gallery-edits/assets/5774411/cdcd4914-ab88-4e2f-90a1-138a632ca2cd)

### Tags

todoist, todo, productivity, task-manager

### Bundled libraries

`requests`

**Comment by vitorgalvao** [comment]
In addition to the cut shadow problem, this one seems like it’s non-retina? Is it an old one?

**Comment by vitorgalvao** [comment]
[Same issue with screenshots](https://github.com/alfredapp/gallery-edits/issues/24#issuecomment-1841616488). Plus missing another for rescheduling the task.

**Comment by giovannicoppola** [comment]
✅ 
please let me know if anything is missing.

**Comment by vitorgalvao** [comment]
Thank you. Will be live later today at https://alfred.app/workflows/giovanni/alfredo/.
