### ISSUE TITLE
Submit Workflow: [alfred-readwise]

### ISSUE THREAD

**Issue by giovannicoppola** [alfredapp/gallery-edits#24]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/giovannicoppola/alfred-readwise

### Alfred Forum page

https://www.alfredforum.com/topic/20208-introducing-alfred-readwise-%F0%9F%93%9A/

### Gallery page content

List, search, and open your [Readwise](https://readwise.io/) highlights
This workflow requires a [Readwise](https://readwise.io/) account.

## Usage
List and search your highlights via the `!r` keyword
![alfred-readwise](https://github.com/alfredapp/gallery-edits/assets/5774411/107c8e3d-15d3-4e7e-b9ec-a9411a949e5b)

`#` will prompt a label search which can be added to the standard search, multiple labels supported
![alfred-readwise2](https://github.com/alfredapp/gallery-edits/assets/5774411/05e0f076-7956-4bdb-ab3a-a70797052bf4)

* <kbd>↩</kbd>: Show the highlight in large font and copy to clipboard
* <kbd>⇧</kbd><kbd>↩</kbd>: Show the highlight in large font and copy to clipboard without closing Alfred
* <kbd>⌘</kbd><kbd>↩</kbd>: Open the source URL if available (typically for tweets)
* <kbd>^</kbd><kbd>↩</kbd>: Open the highlight on Readwise
* <kbd>⇧</kbd><kbd>^</kbd><kbd>↩</kbd>: Open all highlights from that book on Readwise
* <kbd>⌘</kbd><kbd>Y</kbd> (or tap <kbd>⇧</kbd>): Quick Look your highlight

Create new highlights by selecting text in any app via the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/)
![universalAction](https://github.com/alfredapp/gallery-edits/assets/5774411/34603073-1c2c-4b3b-93fa-e0f4839c44ff)

### Tags

readwise, quotes

### Homebrew dependencies

[Pillow](https://formulae.brew.sh/formula/pillow)

### Bundled libraries

`requests`

**Comment by giovannicoppola** [comment]
sorry! I was being lazy

**Comment by vitorgalvao** [comment]
The new screenshots also have issues, there’s a distracting blur at each of the four corners. I tried fixing those but it takes an inordinate amount of time and isn’t perfect. Please use one of the main themes, such as `Alfred Modern`, for the screenshots. That way I can also help with missing screenshots, [like I could with ZotHero](https://github.com/alfredapp/gallery-edits/issues/21#issuecomment-1841614290) because I had all necessary details.

Other issues:

* There’s a screenshot missing for the Universal Action.
* The screenshot was activated via a Hotkey. They should *always* be invoked by typing the keyword, otherwise new users won’t understand how to get to the state in the screenshot.

**Comment by giovannicoppola** [comment]
I have added new images. The hotkey disappears when searching labels, I have added an example without labels.

**Comment by vitorgalvao** [comment]
It’s not clear from looking at the workflow which steps takes one from `!r` to that `#` section. What’s missing between those? Also, in testing I bumped into this:

```
Code 1: /Users/vm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8C289541-5026-4923-97BD-CF23B631B5F5/lib/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/Users/vm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8C289541-5026-4923-97BD-CF23B631B5F5/readwise-query.py", line 17, in <module>
    from readwise_fun import refreshReadwiseDatabase, makeLabelList
  File "/Users/vm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8C289541-5026-4923-97BD-CF23B631B5F5/readwise_fun.py", line 19, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'
```

Does this require a Homebrew Python instead of the one which ships with macOS? That’s important to mention. And is a library missing? `pillow` can be installed with Homebrew, perhaps that’s what you did?

**Comment by giovannicoppola** [comment]
sorry I added this feature upon a user request and I forgot to add this library to `requirements.txt`. However I just tried and it fails, so it will take a little while to figure it out. Also, I am happy to share my readwise token so you can test.

**Comment by vitorgalvao** [comment]
> However I just tried and it fails, so it will take a little while to figure it out.

The conversation at https://github.com/alfredapp/gallery-edits/issues/2 might be relevant.

> Also, I am happy to share my readwise token so you can test.

That would help, thank you. No rush, whenever you feel this is ready for me to take another look.

**Comment by vitorgalvao** [comment]
Thank you. Will be live today at http://alfred.app/workflows/giovanni/readwise/.
