### ISSUE TITLE
Suggest Edit: alfredapp/1password

### ISSUE THREAD

**Issue by diegomichel** [alfredapp/gallery-edits#25]
### Gallery URL

https://alfred.app/workflows/alfredapp/1password/

### About

Add requirements for the workflow to work:

Requirements: [Install the Automation Tasks](https://www.alfredapp.com/help/workflows/automations/automation-task/#update).

**Comment by vitorgalvao** [comment]
Thank you for the suggestion, but this will be addressed another way later.
