### ISSUE TITLE
Suggest Edit: fedecalendino/world-clock

### ISSUE THREAD

**Issue by vbshubham** [alfredapp/gallery-edits#26]
### Gallery URL

https://alfred.app/workflows/fedecalendino/world-clock/

### About

The current globe icon takes up a significant amount of space without offering much information. I propose replacing it with the respective country flag. This adjustment would allow users to quickly identify the correct timezone at a glance.

**Comment by vitorgalvao** [comment]
If you want to request a new feature for a workflow, click the `Website` link and contact the workflow’s creator. The link you clicked is to suggest edits to the Gallery page.
