### ISSUE TITLE
Submit Workflow: Audio Switcher

### ISSUE THREAD

**Issue by TobiasMende** [alfredapp/gallery-edits#27]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/TobiasMende/alfred-audio-switcher

### Alfred Forum page

https://www.alfredforum.com/topic/21244-audio-switcher-swiftly-switch-audio-output-and-input-devices/

## Usage
Quickly switch between audio output devices (like speakers) with `out` and audio input devices (like microphones) with `in`. – Keywords are configurable.  

<img width="764" alt="output" src="https://github.com/alfredapp/gallery-edits/assets/1168406/10a45bd9-42d7-47db-8e16-1f62201776eb">

<img width="764" alt="input" src="https://github.com/alfredapp/gallery-edits/assets/1168406/f6dae8ee-279e-459b-9ce7-fa37b8acbb3d">

The workflow also allows filtering out devices that should not show up in the suggestions. This can be done in the workflow configuration. To make this easier, the `fetchaudiodevices` can be used to copy names of output or input devices to the clipboard.

<img width="764" alt="fetchaudiodevices" src="https://github.com/alfredapp/gallery-edits/assets/1168406/4cf75819-6232-4901-bf98-7040b2d98655">

### Hotkeys
Configure the [Hotkeys](https://www.alfredapp.com/help/workflows/triggers/hotkey/) for faster selection of up to three input and three output devices.

### Remote
This workflow comes with a Remote page and actions can be used in individual Remote pages, too.

There are actions to select the three favorite inputs and three favorite outputs as well as one action to trigger the input selection and one for the output selection.

<img width="578" alt="remote" src="https://github.com/alfredapp/gallery-edits/assets/1168406/8c032216-611d-4ec1-9555-28abda015ddc">

### Configuration Example
<img width="523" alt="configuration" src="https://github.com/alfredapp/gallery-edits/assets/1168406/0f472982-2b4b-460e-825a-cd486e0826f7">

### Tags

audio, sound, audio input, audio output, hotkeys, remote

**Comment by vitorgalvao** [comment]
Second screenshot is showing `input` instead of the real default of `in`. Third screenshot should not have the input text selected.

Other than that it looks good. After those are replaced this will be good to go.

**Comment by TobiasMende** [comment]
Thanks for the quick response! 
I changed the keyword for the screenshot to now show a lot of other results, too. Is there another way to prevent it or would it be okay to cut the image? :-)

**Comment by vitorgalvao** [comment]
That’s OK, then, I can edit that one. Fixing the third one will be enough.

But for future reference, a quick way to solve that is to temporarily reduce the number of visible Alfred results in Alfred Preferences → Appearance → Options → I want to see [N] visible result item.

**Comment by TobiasMende** [comment]
Thank you! I updated both images. :-)

**Comment by vitorgalvao** [comment]
Thank you. Will be live later today at https://alfred.app/workflows/tobiasmende/audio-switcher/.
