### ISSUE TITLE
Suggest Edit: alfredapp/deep-contacts-search

### ISSUE THREAD

**Issue by Gordis60** [alfredapp/gallery-edits#28]
### Gallery URL

https://alfred.app/workflows/alfredapp/deep-contacts-search/

### About

This workflow doesn't work for me

### Notes

In Alfred I write dc followed by a value to search for. To which I add something after "dc I get the menu configured in fallback of Alfred's options

**Comment by vitorgalvao** [comment]
Hello,

The `Edit Page` link is to report inaccuracies *in the Gallery page itself*. For reporting workflow issues, please use the `Website` link and report it there. Please include the [debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) output, as well as your versions of Alfred and the workflow.

But first, please make sure Alfred has access to your contacts under Privacy in System Settings. If it does, [regrant permissions](https://www.alfredapp.com/help/getting-started/permissions/#regrant) and try again. See also “[Alfred isn't finding my Contacts, or is showing duplicates](https://www.alfredapp.com/help/troubleshooting/finding-contacts/)”.
