### ISSUE TITLE
Submit Workflow: Supercharged Citation Picker

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#3]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/chrisgrieser/alfred-bibtex-citation-picker

### Alfred Forum page

https://www.alfredforum.com/topic/18092-supercharged-citation-picker/

### Gallery page content

<img width="1106" alt="Pasted image 2023-07-20 at 21 09 44@2x" src="https://github.com/alfredapp/gallery-edits/assets/73286100/0f724c13-b200-472d-8c81-6620c745458b">

## Feature Overview
- Inserts __Pandoc Citation Syntax__ (`[@citekey]`), supporting page numbers & multiple citations (`[@citekey, p. 23; @citekey, p. 42]`). Can also be configured to use __LaTeX__, __Multi-Markdown__, __eta templates__, __Org Mode__, `[[wikilinks]]`, `#tags` or `bare citkeys` as citation format.
- __App-independent:__ Works system-wide, in every text field of every app.
- __Smart Search:__ Search for citekeys, authors, title, publication, keywords (tags), include or exclude authors in *et al.*, tab-completion, fuzzy-matching, sorting recently used entries to the top.
- __Feature-rich:__ Paste single-entry bibliographies, open URLs, open or create literature notes, attach PDFs, search for `.csl` files online, and more.
- __Blazingly Fast:__ Considerably quicker than any other citation picker (~200 ms to fully reload a library with ~4000 entries).
- __Simple Installation:__ Just enter the path to your `.bib` file, and you are ready to go.
- __Lightweight Reference Manager:__ Automatically rename and file PDFs, remove, entries, and more.
- __Quickly Add New Entries:__ Select a DOI or ISBN and add them directly to your BibTeX library via hotkey.
- __Obsidian Integration:__ When located in your [Obsidian Vault](https://obsidian.md/), literature notes are automatically opened or created in Obsidian instead of the default markdown app.

## Basic Usage
Press the [hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) in any text field to start the citation picker. Alternatively, use the `ct` keyword.

### Search
- You can search for the title, author/editor (last name), year, collection, or journal name.
- Prepend `@` to a word to search for a citekey, for example `@Grieser2020`.
- Prepend `#` to search for keywords (tags), for example `#sociology`.
- *Smart Queries*: You can search for any combination of the above. For example, the query `2020 #cognition grieser` searches for entries published in 2020, with the tag "cognition," and with "Grieser" as author/editor.

### Citation Actions
- <kbd>⏎</kbd>: Paste the citekey of the selected citation.
- <kbd>⌥</kbd><kbd>⏎</kbd>: Add another citation.
- <kbd>⇧</kbd><kbd>⌘</kbd><kbd>↵</kbd>: Paste an inline-citation (citation without surrounding formatting, for example `@Grieser2022` instead of `[@Grieser2022]`)
- <kbd>⌘</kbd><kbd>⏎</kbd>: Add page numbers before pasting the selected citekey.
    - Confirm the page number with <kbd>⌥</kbd><kbd>⏎</kbd> (or <kbd>⌘</kbd><kbd>⏎</kbd>) to add another citation afterward.
    - Confirm with <kbd>⇧</kbd><kbd>⌘</kbd><kbd>⏎</kbd> for an inline-citation with page number (`@Grieser2022 [p. 42]`).

### URL Actions
- <kbd>⌃</kbd><kbd>⏎</kbd>: Open the URL in the browser.
- <kbd>⌘</kbd><kbd>C</kbd>: Copy the URL to the clipboard.
- In both cases, if the entry has a DOI but not a URL, the citation picker uses the DOI-URL (`https://doi.org/…`) instead.

## Dozens of More Features
For all the features this workflow has to offer, refer to the [README](https://github.com/chrisgrieser/alfred-bibtex-citation-picker#table-of-contents).

### Tags

academic, citations, reference-management, bibtex, pandoc, markdown, bibliography, literature-management

### Test data

save this as a `.bib` file (github won't let me upload a .bib file)

```bib
@incollection{Granovetter1979,
	title = {The Theory-Gap in Social Network Analysis},
	author = {Granovetter, Mark},
	year = 1979,
	booktitle = {Perspectives on {{Social Network Research}}},
	location = {New York},
	publisher = {Academic Press},
	pages = {501--518},
	editor = {Holland, P. and Leinhardt, S.},
	keywords = {Mikro-Makro-Problem,Netzwerkanalyse,Netzwerktheorie,Theoriel{\"u}cke}
}
@article{Granovetter1983,
	title = {The {{Strength}} of {{Weak Ties}}: {{A Network Theory Revisited}}},
	author = {Granovetter, Mark},
	year = 1983,
	journal = {Sociological Theory},
	volume = 1,
	pages = {201--233},
	doi = {10.2307/202051},
	url = {http://www.jstor.org/discover/10.2307/202051?
	keywords = {Arbeitsplatzmobilit{\"a}t,Netzwerkanalyse,Transitivit{\"a}t,weak ties}
}
@article{WalkerEtAl2022,
	keywords = {Corona, Wissenschaftssoziologie},
	author = {James Walker and Chris Brewster and Rita Fontinha and Washika Haak-Saheem and Stefano Benigni and Fabio Lamperti and Dalila Ribaudo},
	doi = {10.1016/j.respol.2021.104369},
	journal = {Research Policy},
	number = {1},
	pages = {104369},
	publisher = {Elsevier {BV}},
	title = {The unintended consequences of the pandemic on non-pandemic research activities},
	volume = {51},
	year = 2022
}
@article{Swedberg2020,
	keywords = {Wissenschaftstheorie, Begriffstheorie},
	author = {Richard Swedberg},
	doi = {10.1177/1368431019831855},
	journal = {European Journal of Social Theory},
	number = {3},
	pages = {431--445},
	publisher = {{SAGE}},
	title = {On the use of definitions in sociology},
	url = {http://dx.doi.org/10.1177/1368431019831855},
	volume = {23},
	year = 2020
}
```

For an example PDF, you could add this as a new entry: https://doi.org/10.1080/03085140902786827

and then add the PDF here: https://www.researchgate.net/publication/249006197_The_Role_of_Venture_Capital_Firms_in_Silicon_Valley's_Complex_Innovation_Network

### Homebrew dependencies

pdfgrep
pandoc

**Comment by chrisgrieser** [comment]
edited screenshot to include the keyword

**Comment by vitorgalvao** [comment]
> (github won't let me upload a .bib file)

The trick for every format that GitHub doesn’t let you attach is to zip it first. I have added that as tip to the form.

None of the below is blocking, but a few tips:

I’ve noticed you’re expanding tildes, e.g. `bibtex_library_path="${bibtex_library_path/#\~/$HOME}"`, [but that is not necessary](https://www.alfredapp.com/help/workflows/workflow-configuration/#:~:text=The%20File%20Picker%20configuration%20previews%20the%20home%20folder%20as%20~%2C%20but%20the%20Workflow%20sees%20the%20real%20%2FUsers%2F%5Busername%5D%20path.):

> The File Picker configuration previews the home folder as `~`, but the Workflow sees the real `/Users/[username]` path.

Another thing I’ve noticed was expanding the `PATH` to include Homebrew locations: `export PATH=/usr/local/bin/:/opt/homebrew/bin/:$PATH`. That is also not necessary, [as Alfred already includes those](https://www.alfredapp.com/help/workflows/advanced/understanding-scripting-environment/#:~:text=Its%20PATH%20is). Due to that, the code above will result in `/usr/local/bin/:/opt/homebrew/bin/:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`.

But as I said, not blocking. With README tweaks, it will be live later today at https://alfred.app/workflows/chrisgrieser/supercharged-citation-picker/.

Thank you.

**Comment by chrisgrieser** [comment]
Ah, good thing, thank you! I think I always do those two things since earlier versions of Alfred (3 or 4?) still required that. Didn't get the memo that they weren't required and just kept the habit I guess. 👍
