### ISSUE TITLE
Suggest Edit: chrisgrieser / Supercharged Citation Picker

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#30]
### Gallery URL

https://alfred.app/workflows/chrisgrieser/supercharged-citation-picker/

### Notes

**[As noticable in this forum thread](https://www.alfredforum.com/topic/2224-reference-importer/page/3/#comment-111594)**, it is not apparent from the Gallery Page that the citation picker can do more than just inserting citation ;) (Though the name does not convey it, sure – feature creep is real I guess.)

Not sure how much should go on the Gallery page, but I think the section "Feature Overview" and "Table of Contents" here, maybe together with an easier to find link to the

Also, I think it might make sense to drop the retirement for pandoc. It's only needed for an auxiliary feature that maybe 20% of the users are using. Telling the remaining  80% to install a dependency they'll never use feels unnecessary. The workflow already notifies the user when they are trying to use the feature without having pandoc installed.

**Comment by vitorgalvao** [comment]
[Page revamped](https://alfred.app/workflows/chrisgrieser/supercharged-citation-picker/). If you feel some clarification is still needed, might be easier to [edit the README and send it back](https://github.com/alfredapp/gallery-edits/files/14449417/citation-readme.md).
