### ISSUE TITLE
Suggest Edit: Update benjaminoddou/emoji-wine

### ISSUE THREAD

**Issue by BenjaminOddou** [alfredapp/gallery-edits#32]
### Gallery URL

https://alfred.app/workflows/benjaminoddou/emoji-wine/

### About

Update workflow to v1.4.0. See [here](https://github.com/BenjaminOddou/alfred-emoji-wine/releases). 😄

**Comment by vitorgalvao** [comment]
Thank you. GitHub has been odd about feeds, not keeping them consistent. Yours and a few others seem particularly affected, which seems to be correlated with the use or emoji and/or images in the feeds, though I can’t say for sure yet.

Update is live.

**Comment by BenjaminOddou** [comment]
You're the best @vitorgalvao ! Many thanks 🙏
