### ISSUE TITLE
Save 'ur note

### ISSUE THREAD

**Issue by Stephen-Lon** [alfredapp/gallery-edits#33]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/Stephen-Lon/Alfred-workflow-save-ur-note/releases/latest/download/save.ur.note.alfredworkflow

### Alfred Forum page

https://www.alfredforum.com/topic/21263-save-ur-note/

### Gallery page content

Save, view and edit quick notes in a single plain text file

This workflow requires Alfred 5.5.

### Create

Save a quick one line note via the `cqn` keyword.
<img width="764" alt="cqn" src="https://github.com/alfredapp/gallery-edits/assets/111967061/2246e0ae-befc-4fdf-b846-3fb150c77b50">

Alternatively save a multi-line note with the `cqp` keyword and then <kbd>⏎</kbd>.
<img width="764" alt="cqp" src="https://github.com/alfredapp/gallery-edits/assets/111967061/51b55713-c852-4358-9509-8f51040c4aa8">
<img width="764" alt="UA text" src="https://github.com/alfredapp/gallery-edits/assets/111967061/4b13bdf3-cc77-45ec-9259-29b84be368b2">

<kbd>⏎</kbd> New paragraph.

<kbd>⌘</kbd><kbd>⏎</kbd> Save text

Alternatively, create a new note from a selection or [Clipboard History](https://www.alfredapp.com/help/features/clipboard/) with the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/).
<img width="764" alt="UA" src="https://github.com/alfredapp/gallery-edits/assets/111967061/eaf3d4e0-d595-4699-843d-4cb3f8715b8b">

### View

View your quick notes with the `vqn` keyword.
<img width="764" alt="vqn" src="https://github.com/alfredapp/gallery-edits/assets/111967061/80475faf-0c54-4362-b826-ec339bbec3e5">

<kbd>⌘</kbd><kbd>⏎</kbd> Edit the QuickNote file.

### Edit

Edit the QuickNote file with the `eqn` keyword.
<img width="764" alt="eqn" src="https://github.com/alfredapp/gallery-edits/assets/111967061/9321d1da-effd-41fa-b28b-ea943572fe09">

<kbd>⏎</kbd> New paragraph

<kbd>⌘</kbd><kbd>⏎</kbd> Save text

### Delete

Delete the QuickNote file with the keyword `dqn`.
<img width="764" alt="dqn" src="https://github.com/alfredapp/gallery-edits/assets/111967061/a6336a55-317d-449d-a604-69a58aa93730">

### Tags

Quick notes, plain text notes

**Comment by vitorgalvao** [comment]
[Reminder](https://github.com/alfredapp/gallery-edits/issues/31#issuecomment-1986187028) on the homepage link:

> when providing links to workflows please always provide the home of the repo instead of a direct link to the download. I get that the direct download is useful to regular users, but for my needs the repo’s home is always best.

Also, the screenshots contain lorem ipsum, but [fake data should be explicitly avoided](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Taking%20Good%20Screenshots.md) so I had to redo those.

Page will be live later today.
