### ISSUE TITLE
Submit Workflow: Save 'ur URL

### ISSUE THREAD

**Issue by Stephen-Lon** [alfredapp/gallery-edits#34]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/Stephen-Lon/Alfred-workflow-save-ur-url

### Alfred Forum page

https://www.alfredforum.com/topic/20802-save-ur-url/

### Gallery page content

Save, view, edit and search URLs in a single plain text or markdown file

This workflow requires Alfred 5.5.

### Save

Save a selected URL from your browser or in [Clipboard History](https://www.alfredapp.com/help/features/clipboard/) with the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/).
<img width="764" alt="SaveURL" src="https://github.com/alfredapp/gallery-edits/assets/111967061/525699b9-6d19-43f7-b6d3-dab28051ddc7">
Optionally provide a title (or accept that offered) when using a plain text `Links` file.
<img width="764" alt="TextTitlePrompt" src="https://github.com/alfredapp/gallery-edits/assets/111967061/ccdb84c1-ba9e-4828-9e73-03f9de93bf7e">
You must provide a title if using a markdown `Links` file.
<img width="764" alt="MDTitlePrompt" src="https://github.com/alfredapp/gallery-edits/assets/111967061/2572e1f2-e794-4205-b313-7615da16b895">
### View and clear

View saved links in Alfred’s Text View, or clear all links, with the `links` keyword.
<img width="764" alt="ViewKeyword" src="https://github.com/alfredapp/gallery-edits/assets/111967061/df9a19ec-28ab-48de-92e0-48833bdfa790">

<kbd>⏎</kbd> View `Links` file

<kbd>⌘</kbd><kbd>⏎</kbd> Send `Links` file to Trash and create new empty `Links` file

View using the configuration option to save in plain text:
<img width="764" alt="ViewPlainLinks" src="https://github.com/alfredapp/gallery-edits/assets/111967061/397e4c25-c747-4b57-9d73-58d06ed71374">
View using the configuration option to save in markdown:
<img width="764" alt="ViewMDLinks" src="https://github.com/alfredapp/gallery-edits/assets/111967061/4e5dd3d5-a560-4c03-a8be-d50fbb95ca35">
<kbd>⌘</kbd><kbd>⏎</kbd> Edit the links file (in either case)

Editing a plain text `Links` file opens the file  in Alfred’s Text View and editing a markdown `Links` file opens the file in your default markdown editor.

## Search

Search the URL names in the `Links` file with the keyword `flinks`.
<img width="764" alt="SearchLinks" src="https://github.com/alfredapp/gallery-edits/assets/111967061/eeb0dcef-6631-41c7-9ef7-ec6a7207b3d2">
Select any link to open it in your browser.

### Tags

URL, browser, links

**Comment by vitorgalvao** [comment]
Thank you. Will be live soon.

One thing I noticed, not about the submission but the workflow itself, is that there is a Keyword to delete the links file (right at the bottom: `{var:deleteLinksFile}`) but there’s no configuration for that keyword. I’m guessing you may have forgotten to remove it when adding <kbd>⌘</kbd><kbd>↩</kbd> to `links`?
