### ISSUE TITLE
Suggest Edit: caleb531/youversion-suggest

### ISSUE THREAD

**Issue by caleb531** [alfredapp/gallery-edits#36]
### Gallery URL

https://alfred.app/workflows/caleb531/youversion-suggest/

### Website

https://github.com/caleb531/youversion-suggest-alfred

### Forum

https://www.alfredforum.com/topic/5567-youversion-suggest-look-up-bible-references-quickly-and-easily/

### About

N/A

### Notes

The current "Forum" link takes me to a "You do not have permission to view this topic." page. The correct forum URL is:
https://www.alfredforum.com/topic/5567-youversion-suggest-look-up-bible-references-quickly-and-easily/

**Comment by vitorgalvao** [comment]
Thank you. Fix will be live today.
