### ISSUE TITLE
Submit Workflow: Owledge

### ISSUE THREAD

**Issue by PESauvage** [alfredapp/gallery-edits#37]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/Owledgeapp/owledge-alfred/raw/main/Owledge.alfredworkflow

### Alfred Forum page

https://www.alfredforum.com/topic/21749-owledge-search-across-all-your-professional-tools-all-at-once/#comment-112999

## Usage
Search through all your tools using the power of [Owledge](https://owledge.app) ! 
Simply type `owl` keyword and start searching instantly !

<img width="622" alt="Screenshot 2024-05-01 at 16 13 19" src="https://github.com/alfredapp/gallery-edits/assets/26255890/f7916c53-03f5-41ba-af6d-4a15c1f357a7">

<img width="622" alt="Screenshot 2024-05-01 at 16 06 49" src="https://github.com/alfredapp/gallery-edits/assets/26255890/be0c0b1d-85d4-44de-b3b7-556c33154e38">

## Configuration
Simply add your Workspace ID and API Key that you can found in your Workspace settings. 

Stuck ? Check our detailed documentation [here](https://owledge.notion.site/Use-Alfred-s-workflow-c93bad7b9ccb495c8dbbfa2656eb257d?pvs=4). 

### Tags

Search, Productivity, Notion, Google Drive,

**Comment by vitorgalvao** [comment]
Thank you for the submission, @PESauvage. This is almost ready to go.

Small question: I see in your instructions the *steps* to get an API key, but is there a URL that would take users directly to that page? That would allow linking to it directly from the top of the Gallery page. See for example [TinyPNG](https://alfred.app/workflows/alfredapp/tinypng/) or [PDF Summarizer](https://alfred.app/workflows/chrisgrieser/pdf-summarizer/).

<img width="786" alt="image" src="https://github.com/alfredapp/gallery-edits/assets/1699443/739c46d1-6ab2-4176-9b33-b79ee2d16f12">
<img width="786" alt="image" src="https://github.com/alfredapp/gallery-edits/assets/1699443/f610d625-f013-4ad2-b264-d481a16c2124">

**Comment by PESauvage** [comment]
Unfortunately, that's not possible, because a user can have multiple workspaces, with each one a different API Key.
And the URL to the workspace settings space is different for each workspace, here is how it looks : `https://search.owledge.app/w/unique_workspace_id/settings/api`

The empty `{` has been removed, and the icons has been optimized.
Let me know if that's good for you.

**Comment by vitorgalvao** [comment]
That’s alright, then. This will be live soon at https://alfred.app/workflows/owledge/owledge/
