### ISSUE TITLE
Suggest Edit: chrisgrieser/search-all-the-docs

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#38]
### Gallery URL

https://alfred.app/workflows/chrisgrieser/search-all-the-docs/

### About

Replace this sentence:
> For example, angular foobar searches the Angular DevDocs for “foobar”.

with this sentence:
> For example, `haskell foobar` searches the Haskell DevDocs for “foobar”.

### Notes

Version 2.2.0 uses [aliases from devdocs](https://devdocs.io/help#aliases) as keywords when available. Since now `angular` has a keyword with `ng`, using it as example for a longform keyword would be confusing.

**Comment by vitorgalvao** [comment]
Done. Thank you.
