### ISSUE TITLE
Submit Workflow: Get Latest Files from Trickster

### ISSUE THREAD

**Issue by apparentsoft** [alfredapp/gallery-edits#39]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://dl.apparentsoft.com/trickster/Get%20latest%20files%20from%20Trickster.alfredworkflow

### Alfred Forum page

https://www.alfredforum.com/topic/21817-get-recent-files-updated-trickster-integration-with-alfred-5-and-devonthink-support/

## Usage

Search through recently used files, tracked by Trickster, via the `ttr` keyword. 

<img width="764" alt="Screenshot 2024-04-24 at 23 48 59" src="https://github.com/alfredapp/gallery-edits/assets/189330/530ec939-d745-4c93-99fe-73aaaf595931">

Continue filtering the list from Trickster by typing after a space, for example `ttr 2024` to search files names that contain `2024`.

Has support for entries in Trickster that are sourced from other apps, like from DEVONthink.

* <kbd>↩</kbd> Open the file in the default app.
* <kbd>⌥</kbd><kbd>↩</kbd> For DEVONthink entries, will open them in DEVONthink.
* <kbd>⌃</kbd><kbd>↩</kbd> Browse the file in Alfred to take further action.

You can configure the workflow to assign a custom keyword and constrain the maximum number of results returned from Trickster.

The workflow can be launched via the <kbd>⌘</kbd><kbd>⌥</kbd><kbd>Z</kbd> hotkey

## Setup

This workflow is only useful if you use [Trickster](https://www.apparentsoft.com/trickster) on your Mac. It's even more useful if you also use [DEVONthink](https://www.devontechnologies.com/apps/devonthink).

### Tags

file-management

**Comment by vitorgalvao** [comment]
Thank you, @apparentsoft. Adding it right now; it will be live soon at http://alfred.app/workflows/apparentsoft/get-latest-files-from-trickster/.

One small note (you don’t have to do anything, this is just for reference):

> The workflow can be launched via the <kbd>⌘</kbd><kbd>⌥</kbd><kbd>Z</kbd> hotkey

While you can *suggest* a Hotkey to users, they are stripped from the workflow on import to prevent conflicts.
