### ISSUE TITLE
Issue report

### ISSUE THREAD

**Issue by HarryMMMA** [alfredapp/gallery-edits#40]
### Gallery URL

https://alfred.app/workflows/chrisgrieser/supercharged-citation-picker/

### About

I encourted a very weird bug. When I incert the citation with Enter, the citation key does not transform to the authors' name as expected because of an unexpected space infrom of the year. I do not know how to fix it. When I type the sitation with [@~]form it works well.
![image](https://github.com/alfredapp/gallery-edits/assets/148505778/b058c9b1-8b82-4c09-9ec1-92fd3ae7b513)

**Comment by vitorgalvao** [comment]
The `Edit Page` link is to report inaccuracies *in the Gallery page itself*. For reporting workflow issues, use the `Website` link and report it there.

**Comment by HarryMMMA** [comment]
Copy it. Thanks for your reply
