### ISSUE TITLE
Submit Workflow: Alfred Dieroller

### ISSUE THREAD

**Issue by ahalbert** [alfredapp/gallery-edits#41]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/ahalbert/alfred-dieroller

### Alfred Forum page

https://www.alfredforum.com/topic/21862-dieroller-alfred-workflow-for-tabletop-gaming/

## Usage

This is a workflow for rolling dice and operating on them, suited to Tabletop Games like *Dungeons & Dragons* and *Shadowrun*. Copies result to clipboard. Trigger the workflow via the `roll` keyword. 

### Arguments

 * `X` - Roll one X sided die
 * `XdY` - Roll X number of Y-sided dice
 * `sum` - Sum dice after rolling
 * `topX` - Get X largest dice
 * `bottomX` - Get X smallest dice
 * `>4` - Get number of dice > 4
 * `+x/+y` Add +x and +y to the first two dice rolled 

### Roll 3d6

`roll 3d6`

<img width="605" alt="roll" src="https://github.com/alfredapp/gallery-edits/assets/849804/0fcc993f-39cb-440b-b4c5-7e906bdcec4a">

### Sum Result

`roll 3d6 sum`

<img width="605" alt="sum" src="https://github.com/alfredapp/gallery-edits/assets/849804/a28a7b98-207b-4a59-a06e-4d91b84eb191">

### Roll 4d6, drop lowest

`roll 4d6 top3`

<img width="605" alt="drop" src="https://github.com/alfredapp/gallery-edits/assets/849804/48ab882b-d828-4da4-8030-7da546f8851a">

### Get number of dice > 4

`roll 10d6 >4`

<img width="605" alt="hits" src="https://github.com/alfredapp/gallery-edits/assets/849804/ea60af57-9f71-49ab-b34d-ecea4ee0c293">

### Modify dice

`roll 20 +5`

<img width="605" alt="math1" src="https://github.com/alfredapp/gallery-edits/assets/849804/07f9711a-7ccb-4281-a0e3-ec5e61832564">

`roll 2d20 +3/*5`

<img width="605" alt="math2" src="https://github.com/alfredapp/gallery-edits/assets/849804/a85dec40-4a90-4e80-bb41-a6ff508da590">

### Combine 

`roll 5d20 top2 sum`

<img width="605" alt="combine" src="https://github.com/alfredapp/gallery-edits/assets/849804/3a60fa92-6343-4551-90d5-68763a7067f4">

### Tags

random, gaming

### Homebrew dependencies

N/A

### Bundled libraries

N/A

**Comment by vitorgalvao** [comment]
Thank you for the submission. It will be available soon at https://alfred.app/workflows/ahalbert/die-roller/.
