### ISSUE TITLE
Submit Workflow: Color Picker

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#42]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#115-color-picker

### Alfred Forum page

https://www.alfredforum.com/topic/20843-color-picker/

## Usage

Activate the *Color Sampler* with the keyword `cp` and pick the desired color or view the color history with the keyword preceded by a colon `:cp`.

<img width="550" alt="picker-result" src="https://github.com/alfredapp/gallery-edits/assets/25689591/a960b38e-39fd-427e-8039-1c3b44ae39cd">

<img width="550" alt="Screenshot 2024-06-24 at 14 52 35" src="https://github.com/alfredapp/gallery-edits/assets/25689591/db9678f9-ea56-4984-a4e3-1835b3cae05b">

### Tags

development, design, colors

**Comment by vitorgalvao** [comment]
Thank you. I need just a couple of screenshots more: One with Alfred open with `cp` and another with `:cp`. The Gallery is used by users with a wide range of experience and someone *will* have questions about how to get to that first screenshot otherwise.

If you share the theme you’re using, in the future (or even for this time) I can take those simpler screenshots myself.

**Comment by zeitlings** [comment]
Hey @vitorgalvao 
Here are the missing screenshots and also the theme I'm currently using, just in case. 
I've also updated the workflow to incorporate your suggestion at https://github.com/zeitlings/alfred-workflows/issues/14. Thanks for that btw!

<img width="614" alt="keyword-cp" src="https://github.com/alfredapp/gallery-edits/assets/25689591/82fafafa-31a3-4a6c-9844-c788dcc58c54">
<img width="614" alt="keyword-history" src="https://github.com/alfredapp/gallery-edits/assets/25689591/441c7a26-0cd8-4ec9-a58c-ef8a1848d023">

Theme: https://transfer.archivete.am/KnrIn/zeitlings-light-rounded-small.alfredappearance

**Comment by vitorgalvao** [comment]
Thank you. Good looking theme, too.

Live at http://alfred.app/workflows/zeitlings/color-picker/.
