### ISSUE TITLE
Submit Workflow: Scratchpad

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#43]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#119-scratchpad

### Alfred Forum page

https://www.alfredforum.com/topic/21812-scratchpad/

## Setup

1. Define the two keyboard shortcuts, e.g. <kbd>⌘</kbd><kbd>⌥</kbd><kbd>P</kbd> for the __primary__ entry point and <kbd>⌘</kbd><kbd>⌥</kbd><kbd>⌃</kbd><kbd>P</kbd> for the __secondary__ entry point.
2. Decide on how many scratchpads you would like to use.
3. Select a preferred file extension, if you have one.
4. Optionally select a location where you want the notes to be created and stored.

## Usage 

1. Press the __primary__ [Hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) to open the scratchpad that was last used.  
* Press the Hotkey again or <kbd>⎋</kbd> to dismiss the scratchpad without saving.
2. Press the __secondary__ Hotkey or enter the workflow's [Keyword](https://www.alfredapp.com/help/workflows/inputs/keyword/) `pad` to view all scratchpads and to search their contents. 

<img width="550" alt="markdown-mode" src="https://github.com/alfredapp/gallery-edits/assets/25689591/3cd39179-0a6a-4697-a1d2-3149837b61ac">

In __Editing Mode__
* <kbd>⌘</kbd><kbd>↩</kbd> to save changes.¹
* <kbd>⇧</kbd><kbd>↩</kbd> to preview as rendered markdown.
* <kbd>⌥</kbd><kbd>↩</kbd> to view all pads and search your notes.
* <kbd>⌘</kbd><kbd>⇧</kbd><kbd>↩</kbd> to cycle through your scratchpads.

In __Markdown Mode__
* <kbd>↩</kbd> (or <kbd>⇧</kbd><kbd>↩</kbd>) to start editing.
* <kbd>⌥</kbd><kbd>↩</kbd> to view all pads and search your notes.
* <kbd>⌘</kbd><kbd>⇧</kbd><kbd>↩</kbd> to cycle through your scratchpads.
* <kbd>⎋</kbd> to either cancel or go back through previously viewed pads.

<img width="550" alt="pad-switcher" src="https://github.com/alfredapp/gallery-edits/assets/25689591/15fd7d95-5141-409b-84ac-576eb5b739bb">

<img width="550" alt="pad-search" src="https://github.com/alfredapp/gallery-edits/assets/25689591/9b1abcdd-6d8f-4f92-bb09-c3b2a3c5f2e9">

- __Type__ to filter scratchpads based on your query.²
- <kbd>↩</kbd> to open the pad.
- <kbd>⌘</kbd><kbd>L</kbd> on a filtered pad to view the matched line as [Large Type](https://www.alfredapp.com/help/features/large-type/).
- <kbd>⌘</kbd><kbd>Y</kbd> (or tap <kbd>⇧</kbd>) to Quick Look preview the pad.

---

### Footnotes

¹  Changes are also saved when previewing and when switching the active pad.  
²  When searching for a pad containing a keyword, the first matching line is used as subtitle.

### Tags

markdown, notes

**Comment by vitorgalvao** [comment]
Thank you. This will be available today at http://alfred.app/workflows/zeitlings/scratchpad/.
