### ISSUE TITLE
Submit Workflow: Bluetooth Device Battery

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#44]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#111-bluetooth-device-battery

### Alfred Forum page

https://www.alfredforum.com/topic/20325-bluetooth-device-battery/

## Setup

Download Apple's [SF Pro](https://developer.apple.com/fonts/) font to see the icons.

## Usage

See the battery status of your connected Bluetooth devices via the keyword `btb`.

<img width="550" alt="preview" src="https://github.com/alfredapp/gallery-edits/assets/25689591/a9a1a5c9-08d9-40c8-8ea9-04fd7c452ba1">

### Tags

bluetooth, airpods, hardware

**Comment by vitorgalvao** [comment]
Thank you. Looking good except for a small detail: the instructions and screenshot say to use `btd` (all good) but the workflow itself has `db` set as the default keyword.

**Comment by zeitlings** [comment]
Thanks for pointing out that oversight. It's fixed now: [v1.1.2-btb](https://github.com/zeitlings/alfred-workflows/releases/tag/v1.1.2-btb)

**Comment by vitorgalvao** [comment]
Live at https://alfred.app/workflows/zeitlings/bluetooth-device-battery/.
