### ISSUE TITLE
Submit Workflow: OCR Light

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#47]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#16-alfredocr

### Alfred Forum page

https://www.alfredforum.com/topic/20040-alfredocr-optical-character-recognition/

## Setup

1. Specify the languages you want to recognize in the configuration.
2. Optionally, configure the [Hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) to trigger faster.
- Recommended key-combo: <kbd>⌘</kbd><kbd>⇧</kbd><kbd>6</kbd>

## Usage

To copy text from images to the clipboard, initiate a snapshot via the keyword `ocr` or by using the [Hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/). Alternatively, send an image to the Workflow's [File Action](https://www.alfredapp.com/help/workflows/triggers/file-action/).

__Note:__ URLs detected in QR codes will also be copied to the clipboard.

<img width="550" alt="keyword" src="https://github.com/alfredapp/gallery-edits/assets/25689591/340f7342-0c99-4fac-be85-b3da65a52c26">

<img width="550" alt="fileaction" src="https://github.com/alfredapp/gallery-edits/assets/25689591/1b2cc2f6-ffa4-483f-9fc5-714a5ac86f3f">

### Tags

ocr

**Comment by vitorgalvao** [comment]
Thank you. Live at https://alfred.app/workflows/zeitlings/ocr-light/.
