### ISSUE TITLE
Submit Workflow: Window Navigator

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#48]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#120-window-navigator

### Alfred Forum page

https://www.alfredforum.com/topic/21898-window-navigator/

## Setup

Optionally, configure the [Hotkeys](https://www.alfredapp.com/help/workflows/triggers/hotkey/) for quick access.

## Usage

1. Search the windows of the active app globally via the __Navigator__ keyword `ww` 
2. Search app windows in the current desktop space via the __Switcher__ keyword `ws` 
3. Search all visible windows of all apps globally via the __Global__ keyword `wa`

* <kbd>↩</kbd> Navigate to the selected window.
* <kbd>⌘</kbd><kbd>↩</kbd> Close the selected window.
* <kbd>⌥</kbd><kbd>↩</kbd> Quit the owning application.

### 1. Navigator

<img width="550" alt="navigator" src="https://github.com/alfredapp/gallery-edits/assets/25689591/78b843a6-b18a-4ee9-bd59-9b7383887724">

### 2. Switcher

<img width="550" alt="switcher" src="https://github.com/alfredapp/gallery-edits/assets/25689591/45c0815b-f8d7-4a66-8141-bfbb2565248f">

### 3. Global

<img width="550" alt="global" src="https://github.com/alfredapp/gallery-edits/assets/25689591/08fe2949-427c-4532-b479-d905738217f6">

### Tags

window-management

**Comment by vitorgalvao** [comment]
Thank you. Live at https://alfred.app/workflows/zeitlings/window-navigator/.
