### ISSUE TITLE
Submit Workflow: PDF to Text

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#49]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#116-pdf-to-text

### Alfred Forum page

https://www.alfredforum.com/topic/21764-pdf-to-text

## Usage

Extract the entire text from one or more PDFs by sending them to the workflow's [File Action](https://www.alfredapp.com/help/workflows/triggers/file-action/) or locate a PDF with the [File Filter](https://www.alfredapp.com/help/workflows/inputs/file-filter/) via the keyword `pdftotext`.

### File Filter

![preview_pdftotext-1](https://github.com/alfredapp/gallery-edits/assets/25689591/0b116811-310a-4080-b0e8-f4afaad0722f)

- <kbd>↩</kbd> Proceed to extract the entire text.
- <kbd>⌘</kbd><kbd>↩</kbd> Proceed by specifing the pages to extract.
- <kbd>⌃</kbd><kbd>↩</kbd> Proceed, push the result to the [File Buffer](https://www.alfredapp.com/help/features/file-search/#file-buffer) and [action it in Alfred](https://www.alfredapp.com/help/features/universal-actions/).

### File Action

![preview_pdftotext-2](https://github.com/alfredapp/gallery-edits/assets/25689591/ade28354-3c12-4fdd-8aa5-c6ba706d5a1e)

- <kbd>↩</kbd> Proceed to extract the entire text.
- <kbd>⌘</kbd><kbd>↩</kbd> Proceed by specifing the pages to extract (single file only).
- <kbd>⌃</kbd><kbd>↩</kbd> Proceed, push the result(s) to the [File Buffer](https://www.alfredapp.com/help/features/file-search/#file-buffer) and [action them in Alfred](https://www.alfredapp.com/help/features/universal-actions/).

### Specifying the Pages

<img width="662" alt="preview_pdftotext-3" src="https://github.com/alfredapp/gallery-edits/assets/25689591/33f08b31-9f4b-4daa-a272-dd8b95e15457">

- <kbd>↩</kbd> Proceed to extract text from the specified pages.
- <kbd>⌘</kbd><kbd>↩</kbd> Preview the first and last PDF pages w/ Alfred's PDF View.
- <kbd>⌥</kbd><kbd>↩</kbd> Preview the contents of the first and last page w/ Alfred's Text View.
- <kbd>⌃</kbd><kbd>↩</kbd> Proceed, push the result to the [File Buffer](https://www.alfredapp.com/help/features/file-search/#file-buffer) and [action it in Alfred](https://www.alfredapp.com/help/features/universal-actions/).

<img width="640" alt="preview_pdftotext-4" src="https://github.com/alfredapp/gallery-edits/assets/25689591/2e60773a-0510-471c-831b-48f899daa818">

<img width="662" alt="preview_pdftotext-5" src="https://github.com/alfredapp/gallery-edits/assets/25689591/f273119b-80fd-4cec-a7d6-35458322ae7e">

- <kbd>↩</kbd> Return to the view where you can set the start and end pages.

### Tags

pdf, universal-actions, text-manipulation, academia

### Homebrew dependencies

[poppler](https://formulae.brew.sh/formula/poppler#default)

**Comment by vitorgalvao** [comment]
Live at https://alfred.app/workflows/zeitlings/pdf-to-text/.
