### ISSUE TITLE
Submit Workflow: `Search ALL the docs!`

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#5]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/chrisgrieser/alfred-docs-searches

### Alfred Forum page

https://www.alfredforum.com/topic/20663-search-all-the-docs/

### Gallery page content

<img width="664" alt="showcase pandoc" src="https://github.com/alfredapp/gallery-edits/assets/73286100/64d8366a-1278-4f2d-9bb1-b8693617c3b2">

<img width="1106" alt="showcase git" src="https://github.com/alfredapp/gallery-edits/assets/73286100/32a3786d-7b28-478c-9f25-924c65098b7c">

## Usage
Search more than two dozen developer documentation sites via one of the keywords below.
- <kbd>⏎</kbd>: Open the documentation site.
- <kbd>⌥</kbd><kbd>⏎</kbd>: Copy the Url of the documentation site to the clipboard.

## Documentations Searched
- `css`: MDN
- `html`: MDN
- `js`: MDN
- `jxa`: JavaScript for Automation Cookbook
- `lua`
- `eslint`
- `rome`
- `sc`: shellcheck Wiki
- `pandoc`: Pandoc User Manual
- `git`: official docs & the "pro-git" book
- `py`: python official docs
- `sh`: cheat.sh
- `man`: man pages
- `hs`: Hammerspoon reference
- `sb`: sketchybar docs
- `ke`: Karabiner Elements docs
- `star`: starship prompt docs
- `ep`: espanso docs
- `wt`: WezTerm docs
- `awd`: Alfred Workflow docs

## Extra Utilities
- `coco`: conventional commit keywords
- `keycode`: macOS keycodes
- `appid`: app-id of installed macOS apps
- `code`: Code search on GitHub and SourceGraph
- `http`: HTTP status codes
- `uri`: URI schemes available on the device
- `as`: AppleScript Dictionaries of installed apps
- `sound`: Preview (pre-listen, technically) macOS System Sounds
- Get the Uniform Type Identifier (UTI) of a selected file via the [Universal Action](https://www.alfredapp.com/help/workflows/triggers/universal-actions/)

### Tags

documentation, developer

### Test data

none needed

### Homebrew dependencies

none

### Bundled libraries

none

**Comment by vitorgalvao** [comment]
Thank you. Will be live later today at https://alfred.app/workflows/chrisgrieser/search-all-the-docs/.
