### ISSUE TITLE
Submit Workflow: Anime Search

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#50]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/chrisgrieser/alfred-anime-search

### Alfred Forum page

https://www.alfredforum.com/topic/22070-anime-search-search-the-myanimelist-database/

## Usage
Search all anime listed in the `myanimelist` database via the keyword `an`.
- <kbd>⏎</kbd>: Open at myanimelist.net.
- <kbd>⌘⏎</kbd>: Copy the Japanese (romaji) title.
- <kbd>⌥⏎</kbd>: Copy the `myanimelist` URL.

### Tags

anime, tv, ratings, movies

### Test data

n/a

### Homebrew dependencies

none

### Bundled libraries

none

**Comment by vitorgalvao** [comment]
Thank you. Live now at https://alfred.app/workflows/chrisgrieser/anime-search/.
