### ISSUE TITLE
Submit Workflow: Roman Numeral

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#52]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#13-roman-numeral-converter

### Alfred Forum page

https://www.alfredforum.com/topic/19860-roman-numeral-converter/

## Usage

Convert Roman numerals to Arabic numbers and vice versa via the `rn` keyword.

<img width="550" alt="torn" src="https://github.com/user-attachments/assets/28ec9525-41e7-49f9-bf1d-385143d38297">
<img width="550" alt="todec" src="https://github.com/user-attachments/assets/418d9af8-663c-4438-b48a-9b9d49d2c772">

- <kbd>↩</kbd> (or <kbd>⌘</kbd><kbd>C</kbd>) to copy numeral or number.

### Tags

converter, numbers

**Comment by vitorgalvao** [comment]
Thank you. Live now at https://alfred.app/workflows/zeitlings/roman-numeral/.
