### ISSUE TITLE
Submit Workflow: PDF Compress

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#53]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#118-pdf-compress

### Alfred Forum page

https://www.alfredforum.com/topic/21766-pdf-compress

## Usage

Activate the workflow via the `pdfcompress` keyword to open the [File Filter](https://www.alfredapp.com/help/workflows/inputs/file-filter/) and locate a PDF. 
Alternatively, send a PDF to the workflow's "Compress PDF Document" [Universal Action](https://www.alfredapp.com/help/workflows/triggers/universal-action/). 

### File Filter

<img width="612" alt="pdfcmpr-file-filter" src="https://github.com/user-attachments/assets/e4a65fc0-2ad2-48d3-a826-2f703bf4643e">

- <kbd>↩</kbd> Proceed to compress the PDF using the default strategy.
- <kbd>⌥</kbd><kbd>↩</kbd> Select a compression preset.

### Universal Action

<img width="612" alt="pdfcmpr-universal-action" src="https://github.com/user-attachments/assets/2f7f35ce-7758-443b-92ba-e91904225e30">

- <kbd>↩</kbd> Proceed to compress the PDF using the default strategy.
- <kbd>⌥</kbd><kbd>↩</kbd> Select a compression preset.

### Compression Presets

<img width="612" alt="pdfcmpr-presets" src="https://github.com/user-attachments/assets/3025f740-d53e-4432-9d17-8ec13ab7eee1">

- <kbd>↩</kbd> Proceed to compress the PDF using the selected strategy.

The result will be a compressed document exported to the same location as the source PDF file.

### Tags

pdf, compression, universal-actions

### Homebrew dependencies

[Ghostscript](https://formulae.brew.sh/formula/ghostscript#default)

**Comment by vitorgalvao** [comment]
Live at https://alfred.app/workflows/zeitlings/pdf-compress/.
