### ISSUE TITLE
Submit Workflow: PDF Split

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#54]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#117-pdf-split

### Alfred Forum page

https://www.alfredforum.com/topic/21765-pdf-split

## Usage

Activate the [File Filter](https://www.alfredapp.com/help/workflows/inputs/file-filter/) via the `pdfsplit` keyword and locate a PDF. Alternatively, send a PDF to the workflow's [Universal Action](https://www.alfredapp.com/help/workflows/triggers/universal-action/). Specify the start and end pages of the range you want to be extracted and exported as a new PDF document.

<img width="662" alt="preview_pdfsplit-1" src="https://github.com/user-attachments/assets/cdea5611-b5cf-472e-b82c-3e43496fb07c">
<img width="892" alt="preview_pdfsplit-2" src="https://github.com/user-attachments/assets/6f4ac9de-89fd-4b60-84a2-8230efc84f65">

### Specifying the Pages

<img width="662" alt="preview_pdfsplit-3" src="https://github.com/user-attachments/assets/2540b935-54eb-49b7-918c-3428a395f70d">

- <kbd>↩</kbd> Proceed to create a new PDF from the specified pages.
- <kbd>⌘</kbd><kbd>↩</kbd> Preview the first and last PDF pages w/ Alfred's PDF View.
- <kbd>⌥</kbd><kbd>↩</kbd> Proceed, push the result to the [File Buffer](https://www.alfredapp.com/help/features/file-search/#file-buffer) and [action it in Alfred](https://www.alfredapp.com/help/features/universal-actions/).

<img width="640" alt="preview_pdfsplit-4" src="https://github.com/user-attachments/assets/8f8b841b-c1e9-4b73-9a63-dcba72828a49">

- <kbd>↩</kbd> Return to the view where you can set the start and end pages.

### Tags

pdf, universal-actions, academia

### Homebrew dependencies

[Poppler](https://formulae.brew.sh/formula/poppler#default)

**Comment by vitorgalvao** [comment]
Live at https://alfred.app/workflows/zeitlings/pdf-split/.
