### ISSUE TITLE
Submit Workflow: What Unicode character is this?

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#55]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#12-what-unicode-character-is-this

### Alfred Forum page

https://www.alfredforum.com/topic/19859-what-unicode-character-is-this/

## Usage

Inspect Unicode characters via the keyword `whatisit?`.

<img width="614" alt="Screenshot 2024-07-12 at 11 25 23" src="https://github.com/user-attachments/assets/ef82bb96-cfb5-4e8f-aff0-174803f6bc75">

- <kbd>↩</kbd> Copy the Unicode character.
- <kbd>⌘</kbd><kbd>↩</kbd> Copy the Swift, ES6 formatted code unit (e.g. `\u{30C4}`)
- <kbd>⌥</kbd><kbd>↩</kbd> Copy the Python, Go-lang formatted code unit (e.g. `\u30C4`)
- <kbd>⌃</kbd><kbd>↩</kbd> Copy the HTML entity (e.g. `&#x30C4;`)
- <kbd>⇧</kbd><kbd>↩</kbd> Copy the hex literal (e.g. `0x30C4`)

### Inverse

Specifying a hex value, either raw or in one of the above formats, will return its corresponding Unicode character.

<img width="614" alt="Screenshot 2024-07-12 at 11 25 53" src="https://github.com/user-attachments/assets/ce3bc76e-e269-4832-ba8d-364767e91228">

### Tags

development, reference

**Comment by vitorgalvao** [comment]
Live at https://alfred.app/workflows/zeitlings/what-unicode-character-is-this/.
