### ISSUE TITLE
Submit Workflow: WHOIS Lookup

### ISSUE THREAD

**Issue by FireFingers21** [alfredapp/gallery-edits#57]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/FireFingers21/alfred-whois-lookup

### Alfred Forum page

https://www.alfredforum.com/topic/22036-whois-lookup-perform-a-whois-lookup-in-alfred

## Usage

Perform a [WHOIS](https://en.wikipedia.org/wiki/WHOIS) lookup using the `whois` keyword. Type the domain or IP address you would like to query.

![Using the whois keyword](https://github.com/user-attachments/assets/4bba0536-8f74-4e00-8edb-afe44e08d758)

* <kbd>↩</kbd> View WHOIS data in Alfred's [Text View](https://www.alfredapp.com/help/workflows/user-interface/text/)
* <kbd>⌘</kbd><kbd>↩</kbd> View raw WHOIS data in a text file

The [Text View](https://www.alfredapp.com/help/workflows/user-interface/text/) will try to summarize important information at the top, then display the raw, unmodified data at the bottom. You can choose which information you'd like summarized in the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/).

![Querying alfredapp.com with summary](https://github.com/user-attachments/assets/5b4d8314-6eb4-4fba-aae5-c0db94bb32e1)

![Querying alfredapp.com without summary](https://github.com/user-attachments/assets/8c5e82e1-bef4-41fb-b79e-973f73be11f6)

Configure the [Hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) as a shortcut to perform a WHOIS lookup. Use the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/) to query URLs from Alfred’s [Clipboard History](https://www.alfredapp.com/help/features/clipboard/) or selected text.

![Using the Universal Action](https://github.com/user-attachments/assets/d4fb029b-32ed-4f3c-b73b-e6f34f19c510)

### Tags

reference, web-search

**Comment by vitorgalvao** [comment]
Live at https://alfred.app/workflows/firefingers21/whois-lookup/
