### ISSUE TITLE
Submit Workflow: linkding Bookmarks

### ISSUE THREAD

**Issue by FireFingers21** [alfredapp/gallery-edits#58]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/FireFingers21/alfred-linkding-bookmarks

### Alfred Forum page

https://www.alfredforum.com/topic/21912-linkding-bookmarks-search-linkding-bookmarks-in-alfred

## Setup

Set the Base URL and API Token of your [linkding](https://github.com/sissbruecker/linkding) installation in the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/). You can find the API Token from your linkding Settings → Integrations → Rest API.

## Usage

Search for your [linkding](https://github.com/sissbruecker/linkding) bookmarks using the `bm` keyword.

![Searching for linkding bookmarks](https://github.com/user-attachments/assets/4a2e8a50-a779-49d6-9f43-3694ac65e631)

Type to refine your search. Bookmarks are always filtered by title, while filtering by description, URL, and tags is configurable from the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/).

![Narrowing search for linkding bookmarks](https://github.com/user-attachments/assets/ade62502-703a-4167-af4a-3d6de41ea2ca)

* <kbd>↩</kbd> Open bookmark in primary browser
* <kbd>⌘</kbd><kbd>↩</kbd> Open bookmark in secondary browser
* <kbd>⌥</kbd><kbd>↩</kbd> Edit bookmark in linkding
* <kbd>⇧</kbd><kbd>⌥</kbd><kbd>↩</kbd> View bookmark in linkding
* <kbd>⌃</kbd><kbd>↩</kbd> Delete bookmark from linkding
* <kbd>⌘</kbd><kbd>C</kbd> Copy bookmark URL
* <kbd>⇧</kbd> Hold to show bookmark description

Append `::` to the configured [Keyword](https://www.alfredapp.com/help/workflows/inputs/keyword) to access other actions, including manually reloading the bookmark cache. You can also change the default browser settings from here without using the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/).

![Other actions](https://github.com/user-attachments/assets/93fe860e-4a8a-46f0-a13b-37092960d5fe)

Enable bookmark auto-updates from the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/). Bookmarks will reload upon [Workflow Trigger](https://www.alfredapp.com/help/workflows/triggers/). See a timestamp of the last successful reload from the other actions as shown in the image above.

Configure the [Hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) as a shortcut to search for your bookmarks. Use the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/) to bookmark URLs from Alfred’s [Clipboard History](https://www.alfredapp.com/help/features/clipboard/) or selected text.

![Using the Universal Action](https://github.com/user-attachments/assets/d2e6c446-7b05-438c-82b1-3c848a893e6f)

Bookmarks with the tag `Exclude-Alfred` will be hidden from search. This tag is case sensitive.

### Tags

bookmarks, self-hosted

### Homebrew dependencies

jq

**Comment by vitorgalvao** [comment]
Thank you. Live now at https://alfred.app/workflows/firefingers21/linkding-bookmarks/
