### ISSUE TITLE
Submit Workflow: QResolve

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#59]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#112-qresolve

### Alfred Forum page

https://www.alfredforum.com/topic/20395-qresolve-open-links-from-qr-codes/

## Usage

Take a screenshot of the QR code from which you want to open the link via the `qrr` keyword. Alternatively, send an image containing the QR code to the workflow's [Universal Action](https://www.alfredapp.com/help/workflows/triggers/universal-action/).

<img width="614" alt="keyword" src="https://github.com/user-attachments/assets/d57ce4c0-8c31-4943-95ce-20a4d7dbc183">
<img width="614" alt="universal-action" src="https://github.com/user-attachments/assets/cd088e21-fe12-48c3-b1f7-8694043fd3a3">

Configure the [Hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) to trigger faster.

### Tags

qr-code, universal-actions

**Comment by vitorgalvao** [comment]
Live at https://alfred.app/workflows/zeitlings/qresolve/
