### ISSUE TITLE
Submit Workflow: New File

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#60]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#18-new-file

### Alfred Forum page

https://www.alfredforum.com/topic/20228-new-file

## Usage

Create a new file in your most recent Finder location via the `new` keyword. Alternatively, configure the [Hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) to initiate creating a new file or to create it immediately if the *post-haste* behaviour is enabled in the [Workflow Configuration](https://www.alfredapp.com/help/workflows/workflow-configuration/).

<img width="614" alt="nf-1" src="https://github.com/user-attachments/assets/90c56a27-ebef-4360-ba72-73c48aa83c70">

- <kbd>↩</kbd> Begin creating a new file.
- <kbd>⌘</kbd><kbd>↩</kbd> Search and select the location of the new file.

### Creating a New File

<img width="614" alt="nf-2" src="https://github.com/user-attachments/assets/d5002eb1-d1cd-4e00-8666-7254897701b2">

- <kbd>↩</kbd> Create the file with the given parameters.
- <kbd>⌘</kbd> Hold to view the full path of the target folder.
- <kbd>⌘</kbd><kbd>⇧</kbd><kbd>↩</kbd> Create the file **with clipboard** contents.
- <kbd>⌥</kbd><kbd>⇧</kbd><kbd>↩</kbd> Create the file **without clipboard** contents.
- <kbd>TAB</kbd> Accept and expand the auto-suggested filename.

**Bonus:** In addition to all plain-text type files, the workflow can also quickly create `docx`, `doc`, `odt`, `rtf`, `rtfd` files and Xcode `playground`s.

### Tags

file-management

**Comment by vitorgalvao** [comment]
Thank you. Live at https://alfred.app/workflows/zeitlings/new-file/

**Comment by zeitlings** [comment]
Thanks! I just noticed a minor error: 

> <kbd>⇥</kbd> Accept and expand the auto-suggested filename.

should be:

> <kbd>⇥</kbd> Accept and expand the auto-suggested file **extension**.

The fix for the cache setup is also on the way.

**Comment by vitorgalvao** [comment]
> I just noticed a minor error

Technically the workflow does suggest the filename, _extension included_, so doesn’t seem like an issue. But I’ll make the change if you prefer that.

**Comment by zeitlings** [comment]
Hm, yes I would prefer that, since the only filename that will be substituted is "untitled" if no filename is specified at all, otherwise the specified name will always be used. Merci
