### ISSUE TITLE
Submit Workflow: Keyboard Brightness

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#61]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#19-keyboard-brightness

### Alfred Forum page

https://www.alfredforum.com/topic/20275-keyboard-brightness/

## Usage 

Change the brightness of the keyboard backlight via the `keybr` keyword.

<img width="614" alt="Screenshot 2024-07-17 at 14 27 42" src="https://github.com/user-attachments/assets/4b2ad6a2-d428-4969-ae4d-a646986425f5">

- <kbd>></kbd> (or <kbd>+</kbd>) Increase the brightness.
- <kbd><</kbd> (or <kbd>-</kbd>) Decrease the brightness.

Alternatively, configure the [Hotkeys](https://www.alfredapp.com/help/workflows/triggers/hotkey/) to adjust the brightness with keyboard shortcuts.

### Tags

system

**Comment by vitorgalvao** [comment]
Live at https://alfred.app/workflows/zeitlings/keyboard-brightness/
