### ISSUE TITLE
Submit Workflow: GIF from Video

### ISSUE THREAD

**Issue by zeitlings** [alfredapp/gallery-edits#62]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/zeitlings/alfred-workflows#110-gif-from-video

### Alfred Forum page

https://www.alfredforum.com/topic/20284-generate-gifs-from-video/

## Usage 

Find a video to convert to GIF with [ffmpeg](https://ffmpeg.org/) via they `gifify` keyword. 

<img width="614" alt="keyword" src="https://github.com/user-attachments/assets/2f50c893-6746-4fa9-b43d-5d7a87ccabe5">

Alternatively, convert video files using the [Universal Action](https://www.alfredapp.com/help/workflows/triggers/universal-action/).

<img width="614" alt="fileaction" src="https://github.com/user-attachments/assets/01f67846-ecbe-44a4-a1f0-e71b4db8f4d0">

Select the size of the resulting GIF from the list.

<img width="614" alt="dimensions" src="https://github.com/user-attachments/assets/76907b78-44ff-4db7-bb2f-0d32ebc497c4">

- <kbd>↩</kbd> Generate GIF.

### Tags

converter, gifs, universal-actions, video

### Homebrew dependencies

[ffmpeg](https://formulae.brew.sh/formula/ffmpeg)

**Comment by vitorgalvao** [comment]
Live at https://alfred.app/workflows/zeitlings/gif-from-video/
