### ISSUE TITLE
Suggest Edit: firefingers21/linkding-bookmarks

### ISSUE THREAD

**Issue by FireFingers21** [alfredapp/gallery-edits#68]
### Gallery URL

https://alfred.app/workflows/firefingers21/linkding-bookmarks/

### About

This paragraph:

> Enable bookmark auto-updates from the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/). Bookmarks will reload upon [Workflow Trigger](https://www.alfredapp.com/help/workflows/triggers/). See a timestamp of the last successful reload from the other actions as shown in the image above.

...should be replaced with these two paragraphs:

> Enable bookmark auto-updates from the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/). Bookmarks will reload upon [Workflow Trigger](https://www.alfredapp.com/help/workflows/triggers/).
> 
> Favicons are also supported, and must be enabled in both the [Workflow’s Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) and your linkding settings (this requires at least linkding version 1.31.1).

Additionally, every screenshot has been updated with improved contrast on top of offering better clarity of my new favicons feature. The direct replacements are provided below:

![Searching for linkding bookmarks](https://github.com/user-attachments/assets/e8dc559d-6014-4ab7-a586-a6a156196c6e)
![Narrowing search for linkding bookmarks](https://github.com/user-attachments/assets/eef375ca-005f-4b53-bd54-e64e445a763b)
![Other actions](https://github.com/user-attachments/assets/d4e6d639-d36d-40e1-9b0e-a7b125bd98c8)
![Using the Universal Action](https://github.com/user-attachments/assets/282bbbbc-b26d-4f32-b3fa-f3489c7466c6)

**Comment by vitorgalvao** [comment]
Thank you. Making edits now, this will be live later today.
