### ISSUE TITLE
Suggest Edit: `chrisgrieser/alfred-atop`

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#7]
### Gallery URL

https://alfred.app/workflows/chrisgrieser/atop/

## update screenshot

<img alt="atop overview showcase" width="70%" src="https://github.com/chrisgrieser/alfred-atop/assets/73286100/688059a7-7878-4928-9164-ee6f8eb43381">

### DNS Switching
<img width="60%" alt="showcase DNS Switching" src="https://github.com/chrisgrieser/alfred-atop/assets/73286100/b4ba04bc-4f30-4e09-8eb9-081af24d6f84">

### Notes

and here my theme:
[Fire & Ice.alfredappearance.zip](https://github.com/alfredapp/gallery-edits/files/12282914/Fire.Ice.alfredappearance.zip)

**Comment by vitorgalvao** [comment]
Thank you. Will be live soon, with the new version.
