### ISSUE TITLE
Suggest Edit: chrisgrieser/quick-file-access

### ISSUE THREAD

**Issue by chrisgrieser** [alfredapp/gallery-edits#70]
### Gallery URL

https://alfred.app/workflows/chrisgrieser/quick-file-access/

### Website

https://github.com/chrisgrieser/alfred-quick-file-access/

### About

Initially, the requirements section of the workflow had a type, `riprgrep` instead of `ripgrep`. 

This has been fixed in the workflow docs in https://github.com/chrisgrieser/alfred-quick-file-access/commit/9cc9585b6cb26bbf5aeb15384bfac543c2205527

However, I forgot this subsequently also has to be fixed in the Gallery. The gallery page, as well as apparently the dependency resolution via Alfred, both still use `riprgrep`. This results in an installation failure, see: https://github.com/chrisgrieser/alfred-quick-file-access/issues/2

Changing to `ripgrep` in all occurrences at the Gallery should fix this.

**Comment by vitorgalvao** [comment]
Thank you. I missed that as well. Fixed.
