### ISSUE TITLE
Submit Workflow: Go to Here

### ISSUE THREAD

**Issue by paulrudy** [alfredapp/gallery-edits#72]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/paulrudy/alfred-go-to-here

### Alfred Forum page

https://www.alfredforum.com/topic/6013-go-to-here

## Usage

Quickly switch the selected path in a MacOS Open/Save/Export/Move dialog based on an Alfred selection.

With an Open/Save/Export/Move dialog active, invoke the workflow with one of these methods for selecting a file or folder path:

Search for a file or folder and apply to the dialog via the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/).

<img width="764" alt="screenshot of Go to Here universal action" src="https://github.com/user-attachments/assets/17ab9777-4a2b-46a3-b661-af34e8985742">

Alternatively, get paths for open Finder windows and tabs with keyword `gtf`, or select a file or folder in Alfred with keyword `gth`. `↩` to apply to the dialog.

<img width="764" alt="screenshot of gtf keyword" src="https://github.com/user-attachments/assets/95fad3aa-e100-4bb9-ae41-98feb578740a">

<img width="764" alt="screenshot of gth keyword" src="https://github.com/user-attachments/assets/a4fc4ba2-f4bd-4a6e-9025-1e13140e80c0">

Advanced users can also use the External Trigger from another workflow (not shown, see below).

The workflow looks for English-language button titles in the dialog. Non-English users can change these strings in the [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/), along with adjusting the speed of execution in case of slower machines.

## Credits

Thanks for help and suggestions: [ahmadt](https://www.alfredforum.com/profile/9334-ahmadt/), [sepulchra](https://www.alfredforum.com/profile/717-sepulchra/), [vitor](https://www.alfredforum.com/profile/1891-vitor/), [jwrc](https://www.alfredforum.com/profile/55950-jwrc/), [tombenz](https://www.alfredforum.com/profile/32208-tombenz/)

Icon credit: [Stash Icons](https://github.com/stash-ui/icons). [MIT License](https://github.com/stash-ui/icons/blob/master/LICENSE)

### Tags

universal-actions, file-management, automation

**Comment by vitorgalvao** [comment]
Forgot to close this, but already live.
