### ISSUE TITLE
Suggest Edit: paulrudy/go-to-here

### ISSUE THREAD

**Issue by paulrudy** [alfredapp/gallery-edits#73]
### Gallery URL

https://alfred.app/workflows/paulrudy/go-to-here/

### About

Might want to switch the `gtf` and `gth` screenshots to reflect the order in which they're mentioned in the text (`gtf` is first).

Here are new screenshots reflecting the new results of `gtf`, and the new icon.

<img width="686" alt="screenshot of universal action" src="https://github.com/user-attachments/assets/90c4a9dd-9895-4c1a-b7ee-5754ef14746a">
<img width="686" alt="screenshot of gtf keyword" src="https://github.com/user-attachments/assets/ad46b978-6a60-40c6-81dd-83864b795ce4">
<img width="686" alt="screenshot of gth keyword" src="https://github.com/user-attachments/assets/3a7fac97-b0b8-4daa-ab57-2410e2039b1f">

**Comment by vitorgalvao** [comment]
Thank you. Edited.
