### ISSUE TITLE
Submit Workflow: Plex

### ISSUE THREAD

**Issue by BenjaminOddou** [alfredapp/gallery-edits#8]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/BenjaminOddou/alfred-plex

### Alfred Forum page

https://www.alfredforum.com/topic/20118-alfred-plex-workflow/

## Note

Consult the Workflow’s [website](https://github.com/BenjaminOddou/alfred-plex) for the full feature set and documentation.

## Setup

Quickly add a server by accessing any XML page from the API, copy the URL and paste it in the Alfred search bar. To display the XML page, you'll need to:

- Sign in to your Plex account in Plex Web App.
- Browse to a library item and click `View XML` button.

Follow the [Plex Documentation](https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/) for more details.

![config](https://github.com/alfredapp/gallery-edits/assets/85166574/6b420b55-bf17-4481-b6c8-16f4ad95b1b3)

## Usage

Launch the workflow via the `plex` keyword.

![menu](https://github.com/alfredapp/gallery-edits/assets/85166574/d992078b-c38c-44a5-a00c-a03434f25446)

From the menu:

- Search medias within your server(s).
- Search medias using [Plex Discover](https://support.plex.tv/articles/discover/).
- Register and manage your plex server(s).
- Manage presets to rapidly find your elements in your libraries.
- Display filter and sort options available within your plex server(s).

Search element within your server(s) typing the name of the media and optionally its type separated by a `/`.

![entry](https://github.com/alfredapp/gallery-edits/assets/85166574/896779c6-870b-41b9-b422-ffe4a148c46d)

<kbd>⏎</kbd> : Display the child element of the media (show, season, collection, actor, director, artist, album, genre).
<kbd>⌘</kbd><kbd>⏎</kbd> : Open the media on the web (excluding genre).
<kbd>⌥</kbd><kbd>⏎</kbd> : Stream the media locally (movie, episode, clip, track, album).
<kbd>⌃</kbd><kbd>⏎</kbd> : Open the media using [Movie and TV Show Search](https://alfred.app/workflows/tmcknight/movie-and-tv-show-search/) (show, movie);

Alternatively, use the available filters and fields to search more precisely within you libraries.

![studio](https://github.com/alfredapp/gallery-edits/assets/85166574/9ae72c98-aaef-4839-a074-c666267ab72d)

![af](https://github.com/alfredapp/gallery-edits/assets/85166574/b1c03454-cbfa-4832-8a1c-b68819ed47ba)

Register and manage your plex servers.

![server](https://github.com/alfredapp/gallery-edits/assets/85166574/e25789df-9f9b-4dde-bc7a-1036487232ce)

Build presets. Don't hesitate to share them by opening a [discussion](https://github.com/BenjaminOddou/alfred-plex/discussions/new/choose).

![presets](https://github.com/alfredapp/gallery-edits/assets/85166574/4eaf7549-d0dd-42d5-8034-a8b0dbf75301)

Get the full list of filters, fields and sort options available for you Plex libraries:

![help](https://github.com/alfredapp/gallery-edits/assets/85166574/22657607-a05d-4b4f-804d-0f627d1f2ea7)

### Tags

plex;plexapi;video;audio;server;movie;tv;music

### Homebrew dependencies

python 3.8

### Bundled libraries

[plexapi](https://pypi.org/project/PlexAPI/)

**Comment by vitorgalvao** [comment]
> Launch the workflow via the `plex` keyword.

The screenshot is showing `splex`.

If you share your theme, in simple situations like this I can make a quick correction myself.

**Comment by BenjaminOddou** [comment]
ah yes indeed sorry I am still using `splex` for myself but the default value is `plex`:

![plex](https://github.com/alfredapp/gallery-edits/assets/85166574/74cbb4a0-1463-4c7e-9a51-458b97be7caf)

**Comment by vitorgalvao** [comment]
Thank you. Will be live later today at https://alfred.app/workflows/benjaminoddou/plex/.
