### ISSUE TITLE
Suggest Edit: Alfred Plex

### ISSUE THREAD

**Issue by BenjaminOddou** [alfredapp/gallery-edits#9]
### Gallery URL

https://alfred.app/workflows/benjaminoddou/plex/

### Website

https://github.com/BenjaminOddou/alfred-plex

### Report Bug

https://github.com/BenjaminOddou/alfred-plex/issues

### Forum

https://www.alfredforum.com/topic/20117-alfred-plex-workflow

### About

Start the workflow with the `plex` keyword and choose `Plex Accounts` → `Connect a new plex account`. Sign in to your [Plex](https://support.plex.tv/) account using your credentials.

![connect](https://github.com/alfredapp/gallery-edits/assets/85166574/c27e51b2-0ab1-41a1-afcb-880dd24b615a)

## new menu screenshot

![menu](https://github.com/alfredapp/gallery-edits/assets/85166574/33153282-ea31-4d93-bc97-dfdfb766e81f)

## Plex Configuration -> Plex Media Servers

![server](https://github.com/alfredapp/gallery-edits/assets/85166574/981164b7-35bb-4bf3-9f2b-edd7851b2064)

## Plex Help section

![plexhelp](https://github.com/alfredapp/gallery-edits/assets/85166574/12636f3c-048c-4c3b-a840-771ab7520ab4)

**Comment by vitorgalvao** [comment]
Thank you. Will be live soon.

**Comment by BenjaminOddou** [comment]
@vitorgalvao many thanks ! Just have one remark : I think the plex media servers section part in the documentation didn't update.

**Comment by vitorgalvao** [comment]
Your browser may have cached the older image cached. Do a force reload (<kbd>⌘</kbd><kbd>⌥</kbd><kbd>R</kbd> in Safari).

**Comment by BenjaminOddou** [comment]
@vitorgalvao, I think the title `Plex Configuration` should be `Plex Media Servers`.

![config](https://github.com/alfredapp/gallery-edits/assets/85166574/40f67b60-6d86-400e-a025-caefc376145a)

**Comment by vitorgalvao** [comment]
Ah, I see what you mean. Fixed.
